### DISCUSSION TITLE
Help Request: Nginx Reverse Proxy + Tailscale + OpenCloud Redirect Loop & Metadata Space Error

### DISCUSSION THREAD

**Discussion by Simonetrandafir** [opencloud-eu/opencloud#1017] [Q&A]
### I'm trying to set up a Tailscale-based internal network to serve:
 - an Angular frontend (served via Nginx),
 - a Node.js backend (/api/),
 - and OpenCloud (/drive/) as a file storage service.

### Everything runs inside Docker Compose, all connected via network_mode: service:tailscale.
However, I'm encountering two issues:
 - A redirect loop on /drive/ when accessed from the browser.
 - A persistent OpenCloud internal error related to missing metadata space.

### I'm using Tailscale to create a private overlay network. My frontend container runs Nginx, which acts as a reverse proxy for:
 - the backend at http://localhost:3000/,
 - and OpenCloud at https://localhost:9090/.

#### nginx.conf
```
server {
    listen localhost:80;  
    server_name _;  

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log warn;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://localhost:3000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ^~ /drive/ {
        rewrite ^/drive(/.*)$ $1 break;
        proxy_pass https://localhost:9090;
        proxy_ssl_verify off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location ~* \.js(\?.*)?$ {
        add_header Content-Type application/javascript;
        default_type application/javascript;
        expires 30d;
        access_log off;
    }

    location ~* \.css(\?.*)?$ {
        add_header Content-Type text/css;
        default_type text/css;
        expires 30d;
        access_log off;
    }

    location ~* \.(ico|png|jpe?g|svg|webp|woff2?|ttf|eot|json|map)$ {
        expires 30d;
        access_log off;
    }
}
```
#### docker-compose.yml
```
services:
  tailscale:
    image: tailscale/tailscale:stable
    network_mode: bridge
    ...

  frontend:
    build:
      context: ./frontend
    network_mode: service:tailscale
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: [tailscale, backend]
    ...

  backend:
    build:
      context: ./backend
    network_mode: service:tailscale
    ...

  opencloud:
    image: opencloudeu/opencloud-rolling:latest
    network_mode: service:tailscale
    environment:
      OC_URL: https://tailscale.my_domain.net/drive/
      PROXY_HTTP_ADDR: 127.0.0.1:9090
      OC_INSECURE: true
      OC_CONFIG_DIR: /etc/opencloud
      OC_DATA_DIR: /var/lib/opencloud
    volumes:
      - ./opencloudDB/config:/etc/opencloud
      - ./opencloudDB/data:/var/lib/opencloud
    command: [ "-c", "opencloud init --force-overwrite --insecure true; opencloud server" ]
```
### Redirect Loop Issue
Even with the rewrite rule in Nginx, the /drive/ path always redirects back to the frontend instead of reaching OpenCloud. If I remove the rewrite rule, the issue becomes worse: /drive/ enters an infinite redirect loop and never resolves.

Error:
```
ERR_TOO_MANY_REDIRECTS
Status Code: 308 Permanent Redirect
Location: https://tailscale.my_domain.net/drive/
```

### OpenCloud Error (in logs)
```
{
  "error": "not found: space jsoncs3-public-share-manager-metadata not found",
  "filters": [
    {
      "type": 2,
      "Term": {
        "Id": {
          "opaque_id": "jsoncs3-public-share-manager-metadata!jsoncs3-public-share-manager-metadata"
        }
      }
    }
  ],
  "message": "failed to list storage spaces"
}
```
## What I Need Help With

 - How should Nginx properly reverse proxy OpenCloud’s /drive/ without causing a redirect loop?
 - What is the correct way to initialize or define the missing jsoncs3-public-share-manager-metadata space?
 - Should I use http:// or https:// in proxy_pass if I'm using OC_INSECURE=true?
 - Is there a best practice for serving OpenCloud behind Nginx with Tailscale + network_mode: service:tailscale?
