### DISCUSSION TITLE
External OIDC (Authentik) Broken with Upgrade form 2.3.0 to 3.0.0

### DISCUSSION THREAD

**Discussion by patchmonkey** [opencloud-eu/opencloud#1052] [Q&A]
I recently pulled the new 3.0.0 docker containers and my installation broke. I had successfully configured OpenCloud with Authentik after struggling with it for a long time, but the upgrade prevents my account (primary admin user) from logging in. 

The errors I get in the docker container when I try to log in are:

```
{"level":"error","service":"proxy","request-id":"1a7b3d15-be06-4f4d-89c9-6fca71bacdb7","userid":"bbda3d39-c6a9-4364-9d02-efdf8acdb98d","error":"no role in claim maps to an OpenCloud role","time":"2025-06-13T01:32:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/userroles/oidcroles.go:108"}
{"level":"error","service":"proxy","error":"no role in claim maps to an OpenCloud role","time":"2025-06-13T01:32:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/account_resolver.go:174","message":"Could not get user roles"}
```

I haven't changed any configuration. My previously working role assignment in proxy.yaml was and still is:
```
role_assignment:
    driver: oidc
    oidc_role_mapper:
        role_claim: groups
        role_mapping:
            - role_name: admin    # Opencloud role name
              claim_value: admins # Authentik group name
            - role_name: user
              claim_value: authentik users
            - role_name: guest
              claim_value: authentik users
```

I checked the changes on the releases page but couldn't see anything obvious (to me) that would cause this. Is anyone else experiencing anything similar or have an idea what might be causing it?
