### DISCUSSION TITLE
Radicale with OIDC enabled - error 500

### DISCUSSION THREAD

**Discussion by pyl96** [opencloud-eu/opencloud#1054] [Q&A] [answered]
Hello everyone,

I'm running opencloud with docker-compose, authentication is made with Keycloak and FreeIPA.
Everything seems to work fine except the radicale part.

I have a 500 error when I try to reach https://cloud.example.com/caldav/.web/, after the authentication pop-up.

`2025-06-13T06:30:52Z ERR Error mapping role names to role ids error="no roles in user claims" line=github.com/opencloud-eu/opencloud/services/proxy/pkg/userroles/oidcroles.go:84 request-id=40efbafcc1db/2bI5QKajwA-000027 service=proxy userid=myuser
2025-06-13T06:30:52Z ERR Could not get user roles error="no roles in user claims" line=github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/account_resolver.go:174 service=proxy`

Proxy.yaml config
```
additional_policies:
  - name: default
    routes:
      - endpoint: /caldav/
        backend: http://radicale:5232
        remote_user_header: X-Remote-User
        skip_x_access_token: true
        additional_headers:
          - X-Script-Name: /caldav
      - endpoint: /.well-known/caldav
        backend: http://radicale:5232
        remote_user_header: X-Remote-User
        skip_x_access_token: true
        additional_headers:
          - X-Script-Name: /caldav
      - endpoint: /carddav/
        backend: http://radicale:5232
        remote_user_header: X-Remote-User
        skip_x_access_token: true
        additional_headers:
          - X-Script-Name: /carddav
      - endpoint: /.well-known/carddav
        backend: http://radicale:5232
        remote_user_header: X-Remote-User
        skip_x_access_token: true
        additional_headers:
          - X-Script-Name: /carddav
      - endpoint: /caldav/.web/
        backend: http://radicale:5232/
        unprotected: true
        skip_x_access_token: true
        additional_headers:
          - X-Script-Name: /caldav

role_assignment:
    driver: oidc
    oidc_role_mapper:
        role_claim: groups
        role_mapping:
            - role_name: admin
              claim_value: opencloud-admins
            - role_name: spaceadmin
              claim_value: opencloud-spaceadmins
            - role_name: user
              claim_value: opencloud-users
            - role_name: guest
              claim_value: opencloud-guests
```
.env 
```
OC_URL=https://cloud.example.com
OC_INSECURE=true
OC_LOG_LEVEL=INFO
OC_LOG_COLOR=true
OC_LOG_PRETTY=true
START_ADDITIONAL_SERVICES=notifications
GATEWAY_GRPC_ADDR=0.0.0.0:9142
MICRO_REGISTRY_ADDRESS=127.0.0.1:9233
NATS_NATS_HOST=0.0.0.0
NATS_NATS_PORT=9233
PROXY_CSP_CONFIG_FILE_LOCATION=/etc/opencloud/csp.yaml
STORAGE_USERS_ID_CACHE_STORE=nats-js-kv

ADMIN_PASSWORD=admin

OC_OIDC_ISSUER=https://auth.example.comr/realms/example.com
WEB_OIDC_CLIENT_ID=web
OC_EXCLUDE_RUN_SERVICES=idp,idm
WEB_OPTION_ACCOUNT_EDIT_LINK_HREF=https://auth.example.com/realms/example.com/account
PROXY_OIDC_REWRITE_WELLKNOWN=true
PROXY_ENABLE_BASIC_AUTH=true
PROXY_USER_OIDC_CLAIM=preferred_username
PROXY_USER_CS3_CLAIM=username
PROXY_AUTOPROVISION_ACCOUNTS=false
PROXY_AUTOPROVISION_CLAIM_USERNAME=preferred_username
###PROXY_ROLE_ASSIGNMENT_DRIVER=oidc
OC_ADMIN_USER_ID="myuser"
SETTINGS_SETUP_DEFAULT_ASSIGNMENTS=false
GRAPH_ASSIGN_DEFAULT_USER_ROLE=false
GRAPH_USERNAME_MATCH=none

OC_LDAP_URI=ldap://LDAPIP:389
OC_LDAP_SERVER_WRITE_ENABLED=false
FRONTEND_READONLY_USER_ATTRIBUTES="user.onPremisesSamAccountName,user.displayName,user.mail,user.passwordProfile,user.accountEnabled,user.appRoleAs>
OC_LDAP_INSECURE=true
OC_LDAP_BIND_DN=uid=cloud-app,cn=users,cn=accounts,dc=home,dc=example,dc=com
OC_LDAP_BIND_PASSWORD='aStrongPassword'
OC_LDAP_USER_BASE_DN=cn=users,cn=accounts,dc=home,dc=example,dc=com
OC_LDAP_USER_FILTER="(objectclass=inetOrgPerson)"
OC_LDAP_USER_SCHEMA_ID=uid
OC_LDAP_DISABLE_USER_MECHANISM=none
OC_LDAP_GROUP_BASE_DN=cn=groups,cn=accounts,dc=home,dc=example,dc=com
OC_LDAP_GROUP_SCHEMA_ID=gidnumber
```
docker-compose.yaml
```
services:
  opencloud:
    image: opencloudeu/opencloud-rolling:latest
    container_name: opencloud
    entrypoint:
      - /bin/sh
    command: ["-c", "opencloud init || true; opencloud server"]
    env_file:
      - .env
    ports:
      - '9200:9200'
    volumes:
      - /containers/volumes/opencloud/config:/etc/opencloud
      - /containers/volumes/opencloud/data:/var/lib/opencloud
    restart: always

  radicale:
    image: opencloudeu/radicale:latest
    container_name: radicale
    restart: always
    volumes:
      - /containers/volumes/radicale/config:/etc/radicale/config
      - /containers/volumes/radicale/data:/var/lib/radicale
```

Is there something I missed ?
