### DISCUSSION TITLE
403 forbidden during login with Desktop client for Mac OS

### DISCUSSION THREAD

**Discussion by Watashi26** [opencloud-eu/opencloud#1056] [Q&A]
I just set up a docker compose setup (see below) which is working so far. Only the client wont let me login. I'm using nginx proxy manager for encryption which is probaly the reason. I tries setting **`proxy_set_header Host  $host;`** with no success. Any ideas to solve this problem?

**Compose file:**

```
version: "3.9"
services:
  opencloud-rolling:
    image: opencloudeu/opencloud-rolling
    container_name: opencloud
    entrypoint: [ /bin/sh ]
    command: ["-c", "opencloud init --insecure true || true; opencloud server"]
    ports:
      - "444:9200"
    volumes:
      - /srv/dev-disk-by-uuid-1ae66747-0abd-4691-9a7e-c93f8b46f5e6/CLOUD_DATA:/var/lib/opencloud
      - /home/appdata/opencloud/opencloud-config:/etc/opencloud
    environment:
      - IDM_CREATE_DEMO_USERS=false
      - PROXY_HTTP_ADDR=0.0.0.0:9200
      - OC_URL=https://my-cloud.com
      - OCIS_BASE_DATA_PATH=/var/lib/opencloud
    restart: unless-stopped
```
