### DISCUSSION TITLE
question: external OIDC with internal LDAP server (idm) possible?

### DISCUSSION THREAD

**Discussion by georglauterbach** [opencloud-eu/opencloud#1118] [Q&A]
Is using an OIDC Server like Authelia (or Keycloak) possible with the built-in IDM when autoprovisioning, or do I always need to run a separate LDAP server?

UPDATE/EDIT: Changed "IDP" to "IDM" as correctly pointed out by @rhafer

**Comment by rhafer** [comment]
It is technically possible. We just do not document such a setup currently as we have to focus a bit on which combination for internal/external IDPs and  LDAP servers  we actually what to actively support otherwise this gets too much of a maintenance burden.

Adding some technical nit-picking: The "built-in IDP" is lico (https://github.com/libregraph/lico) which is an OIDC Server. The built-in LDAP Server is based on https://github.com/libregraph/idm which is a different component (internally we call that component "idm" not "idp".

**Comment by georglauterbach** [comment]
Thank you very much for letting me know. I'd like to try it out, maybe I can even contribute back to the docs. I was following the docs for Keycloak & OIDC, but I got backend errors when the user should be created. Is there anything I have to additionally?

PS: I will post the errors I see later because I do not have them at hand right now.

**Reply by micbar** [reply]
@georglauterbach 

like @rhafer said, we do not want this setup to be considered as an option because we cannot maintain so many different approaches. Although you can do that on your own, it should not be documented.

**Reply by georglauterbach** [reply]
Other projects have a "community" section that explicitly states that the content is solely community-contributed. Maybe you can consider doing something similar.

---

I have seen a few error messages in the log; would it be okay to ask for guidance on how to deal with them here?

**Reply by rhafer** [reply]
I'd say having it documented here in the Q&A section of the discussion, with some form of indication that is it not "officially supported" by opencloud would be totally fine.

**Reply by mhymny** [reply]
Hey @georglauterbach, have you managed to get it running yet?
Can you share your authelia and opencloud configuration?

**Reply by georglauterbach** [reply]
Will post tomorrow

**Reply by georglauterbach** [reply]
OpenCloud ConfigMap for K8s:

```yaml
---
apiVersion: v1
kind: ConfigMap

metadata:
  name: opencloud-environment

data:
  # ...

  # OIDC

  OC_EXCLUDE_RUN_SERVICES: idp
  PROXY_ENABLE_BASIC_AUTH: 'false'

  OC_OIDC_ISSUER: "https://<AUTH HOSTNAME>"
  EXTERNAL_OIDC_DOMAIN: "<AUTH HOSTNAME>"

  PROXY_OIDC_REWRITE_WELLKNOWN: 'true'
  PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: none

  PROXY_USER_OIDC_CLAIM: preferred_username
  PROXY_USER_CS3_CLAIM: username

  PROXY_AUTOPROVISION_ACCOUNTS: 'true'
  PROXY_AUTOPROVISION_CLAIM_USERNAME: preferred_username
  PROXY_AUTOPROVISION_CLAIM_EMAIL: email
  PROXY_AUTOPROVISION_CLAIM_DISPLAYNAME: name
  PROXY_AUTOPROVISION_CLAIM_GROUPS: groups

  PROXY_ROLE_ASSIGNMENT_DRIVER: default # I'd love to use `oidc`, but https://github.com/opencloud-eu/desktop/issues/217

  GRAPH_ASSIGN_DEFAULT_USER_ROLE: 'true'
  GRAPH_USERNAME_MATCH: none
  GRAPH_LDAP_SERVER_WRITE_ENABLED: 'true'

  WEB_OIDC_CLIENT_ID: OpenCloudWeb
  WEB_OIDC_SCOPE: openid profile email groups
  WEB_OIDC_METADATA_URL: https://<AUTH HOSTNAME>/.well-known/openid-configuration

# the following can be used when https://github.com/opencloud-eu/desktop/issues/217 is resolved
#---
#apiVersion: v1
#kind: ConfigMap
#
#metadata:
#  name: opencloud-configuration
#
#immutable: false
#
#data:
#  proxy.yaml: |
#    role_assignment:
#      driver: oidc
#      oidc_role_mapper:
#        role_claim: groups
#        role_mapping:
#          - role_name: admin
#            claim_value: admin
#          - role_name: user
#            claim_value: user
#          - role_name: guest
#            claim_value: guest
```

Please be aware of [#217](https://github.com/opencloud-eu/desktop/issues/217).

---

Relevant parts of the Authelia configuration:

```yaml
identity_providers:
  oidc:
    clients:
      - # https://docs.opencloud.eu/docs/admin/configuration/authentication-and-user-management/external-idp/

        client_id: OpenCloudWeb
        client_name: OpenCloud Web
        public: true
        redirect_uris:
          - https://<CLOUD HOSTNAME>/
          - https://<CLOUD HOSTNAME>/oidc-callback.html
          - https://<CLOUD HOSTNAME>/oidc-silent-redirect.html
        scopes:
          - openid
          - profile
          - email
          - groups
        grant_types:
          - authorization_code
        response_types:
          - code
        #authorization_policy: allow_users # really depends on your previously configured policies
        consent_mode: implicit
        require_pkce: true
        pkce_challenge_method: S256
        access_token_signed_response_alg: none
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: none

      - client_id: OpenCloudDesktop
        client_name: OpenCloud Desktop
        public: true
        redirect_uris:
          - http://127.0.0.1
          - http://localhost
        scopes:
          - openid
          - email
          - profile
          - groups
          - offline_access
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        authorization_policy: allow_users
        #lifespan: opencloud # depends on your previously configured lifespans
        consent_mode: implicit
        userinfo_signed_response_alg: none

      - client_id: OpenCloudIOS
        client_name: OpenCloud iOS
        public: true
        redirect_uris:
          - oc://ios.opencloud.eu
        scopes:
          - openid
          - email
          - profile
          - groups
          - offline_access
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        authorization_policy: allow_users
        lifespan: opencloud
        consent_mode: implicit
        userinfo_signed_response_alg: none
```
