### DISCUSSION TITLE
Usage alongside NGINX

### DISCUSSION THREAD

**Discussion by SvenC56** [opencloud-eu/opencloud#338] [Q&A] [answered]
Hi,

I'm just trying our Opencloud but cannot go beyond the login screen with this error:

```
failed to verify access token: Get \"https://opencloud.redacted.de/.well-known/openid-configuration\": dial tcp 172.28.0.29:443: connect: connection refused
```

my compose looks like this

```yml
services:
  opencloud:
    image: opencloudeu/opencloud-rolling
    container_name: opencloud
    hostname: "opencloud.redacted.de"
    entrypoint:
      - /bin/sh
    command: ["-c", "opencloud init --insecure true || true; opencloud server"]
    restart: always
    user: "1000"
    networks:
      nginx-net:
    volumes:
    - ./opencloud/data:/var/lib/opencloud
    - ./opencloud/config:/etc/opencloud
    env_file:
    - path: ./opencloud.env
      required: true
```

and the env file like this

```
IDM_CREATE_DEMO_USERS=false
PROXY_TLS=false
OC_URL=https://opencloud.redacted.de
```

seeing the error i suspect that opencloud tries to use the `OC_URL` as a reference but fails with the wrong port since it uses internally port 9200. Coming from the full example i see that traefik is just load balancing port 9200 to 443, so same as my nginx setup. now I'm wondering if i can override the port 9200 with an env variable?

thanks and best regards
Sven
