### DISCUSSION TITLE
NAS storage with SMB/CIFS - generalException: add grant:Failed to set all xattrs: xattr.Set

### DISCUSSION THREAD

**Discussion by vassalloandrea** [opencloud-eu/opencloud#649] [Q&A] [answered]
Hey all 👋 

I have a Proxmox VM running OpenCloud via Docker Compose.
I’m using a CIFS mount to connect to my NAS for file storage. Everything works well except sharing directories, which fails due to the user_xattr limitation.

Here’s my current fstab entry:

` //192.168.11.2/Opencloud  /mnt/opencloud  cifs  credentials=/etc/smb-credentials-vassalloandrea,iocharset=utf8,uid=1000,gid=1000,file_mode=0664,dir_mode=0775,vers=3.0,mfsymlinks,nounix,serverino,mapposix 0 0`

NAS model: [Ubiquiti UNAS Pro](https://eu.store.ui.com/eu/en/products/unas-pro)

This is the error I’m getting:

`opencloud-1 | {"level":"error","service":"graph","graph api":"DrivesDriveItemService","error":"generalException: add grant:Failed to set all xattrs: xattr.Set /var/lib/opencloud/storage/users/users/66f4cb7c-cc92-4e03-8ccf-d5af9daa0516/Family user.oc.grant.u:04390424-d31b-42cf-b720-808693c09fd2: invalid argument","time":"2025-04-11T07:17:28Z","line":"github.com/opencloud-eu/opencloud/services/graph/pkg/service/v0/api_driveitem_permissions.go:223","message":"share creation failed"}`

Do you have any suggestions on how to fix this?

For context: I previously attempted to use NFS inside an unprivileged container before switching to a VM, and encountered the same issue.

**Comment by samuelh2005** [comment, marked as answer]
It is possible to mount NFS on the host that is running Docker and then bind that into a container. I use a UNAS Pro too.

fstab entry:

`10.0.0.22:/var/nfs/shared/ServerStorage  /mnt/server-storage  nfs  rw,nfsvers=3  0  0`

Replace `10.0.0.22` with the IP of your NAS, and replace ServerStorage  with you share name.

Also make sure to grant access to the NFS share. Go to "Settings" > "Services" > "Add NFS Connection". Then in the panel on the right add the IP of your VM (also make sure the VM is attached directly to the network.

One catch I've found is that you must create a file first in your shared folder before mounting it.

And then for your docker container you can do (make sure to configure it properlly for OpenCloud and not Jeknis):

```yaml
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:jdk21
    ports:
      - "0.0.0.0:8080:8080" # Jenkins web UI
      - "0.0.0.0:50000:50000" # Jenkins agent communication
    volumes:
      - /mnt/server-storage/jenkins:/var/jenkins_home # < important, replace the `server-storage/jenkins` with the share name from before and replace `/var/jenkins_home ` with where you want the files to be in the container.
    restart: unless-stopped
    stdin_open: true
    tty: true
    entrypoint: ["/bin/sh", "-c"]
    command: >
      'git config --global --add safe.directory "*" &&
       /usr/bin/tini -- /usr/local/bin/jenkins.sh'
```
