### DISCUSSION TITLE
crowdsec collection for opencloud

### DISCUSSION THREAD

**Discussion by cscholz** [opencloud-eu/opencloud#786] [Ideas]
Is there anyone already working on a crowdsec collection for opencloud?

**Comment by micbar** [comment]
Please explain what crowdsec is and what problem does it solve for openCloud.

**Comment by cscholz** [comment]
CrowdSec is an open-source intrusion prevention system (IPS) that detects suspicious activities in log files and blocks them automatically. It is based on community intelligence: users share information about attackers to protect each other. CrowdSec analyses logs, recognizes patterns such as brute force attacks or port scans and blocks the corresponding IPs. The collected data is processed in a central database and made available as curated blocklists. These lists can be used in firewalls, web servers or applications to prevent attacks at an early stage.

CrowdSec is free, modular and supports many platforms such as Linux, Windows, Docker and Kubernetes. It is suitable for both small servers and large cloud infrastructures.

It can be used to reduce the attack surface of Opencloud if suspicious activity is detected via log patterns

**Reply by tackin** [reply]
It's available as a container as middlware to traefik.

**Reply by micbar** [reply]
This is awesome! How can we contribute to that idea?

**Reply by scetu** [reply]
I believe that this conversation is to prevent false positive bans which can ocur by Crowdsec (looking at you [http-crawl-non_statics](https://app.crowdsec.net/hub/author/crowdsecurity/scenarios/http-crawl-non_statics) scenario), for example by listing big directories in WebUI, Crowdsec can detect this (numerous HTTP requests within short timeframe) as attack scenario and whitelist needs to be applied. 

For example when streaming Plex video with Crowdsec in place, you need to apply [plex-allowlist](https://app.crowdsec.net/hub/author/crowdsecurity/log-parsers/plex-allowlist) otherwise your Plex client accessing Plex server will get banned by Crowdsec due to triggering [http-crawl-non_statics](https://app.crowdsec.net/hub/author/crowdsecurity/scenarios/http-crawl-non_statics) after some time when playing video.

I have just yesterday deployed my instance of Opencloud and had no time to explore it yet (I am currently working to integrate with my Authelia for OIDC), but I am running it via proxy which is having Crowdsec in place and it monitors all trafic via the proxy, thus I will let you know If I will need to whitelist anything.

**Comment by scetu** [comment]
Hey, this is my first draft of whitelist what I currently have in place.

`/etc/crowdsec/parsers/s02-enrich/05-Opencloud-whitelist.yaml`
```
name: custom-whitelist/Opencloud-whitelist
description: "Whitelist events related to Opencloud server"
filter: "evt.Meta.service == 'http' && evt.Meta.log_type in ['http_access-log', 'http_error-log']"
whitelist:
 reason: "Opencloud Whitelist"
 expression:
    - evt.Meta.http_path contains '/remote.php/dav/spaces'
```

I have whitelisted whole `/remote.php/dav/spaces` cause Opencloud is returning multiple "error" codes (405, 401, etc.) and this got me banned.

**Reply by michaelstingl** [reply]
Hi @Scetu,
thanks for sharing the draft!

Just curious — what are your thoughts on the next steps?
Are you planning to open a PR to the official [crowdsecurity/hub](https://github.com/crowdsecurity/hub) repository, or do you see this evolving as a separate community collection?

If helpful, I can provide details about the behavior of specific OpenCloud endpoints in response to certain requests.
For example, some `401 Unauthorized` responses are expected and inform clients that an OIDC token renewal is required — not necessarily malicious behavior.
Might be worth factoring in when tuning the parser or designing the whitelist.

Looking forward to your thoughts!

**Reply by scetu** [reply]
Hi @michaelstingl,

Thanks for jumping in!

I’d like to tighten the expression first - whitelisting all of `/remote.php/dav/spaces` feels too broad but effective for now. Any docs you can share on which endpoints legitimately return `4xx` would really help us craft a safer rule.

I’m keen to open a PR to [crowdsecurity/hub](https://github.com/crowdsecurity/hub) so others starting with Opencloud have a ready-made template once the whitelist is more specific - a good example can be [nextcloud-whitelist](https://app.crowdsec.net/hub/author/crowdsecurity/log-parsers/nextcloud-whitelist).

For now, I am fighting myself with file uploads which sometimes log out user from WebUI, or Basic Auth popup jumps in (when using OIDC) and integrating Opencloud into my homelab, while using mentioned rule.
![image](https://github.com/user-attachments/assets/c40a3563-b8db-462b-82b5-bf5851f235aa)

**Reply by micbar** [reply]
That looks like your OpenIDConnect setup is wrong. The web client does token refresh requests during the upload workflow. Please check if you are allowing your IdP to be connect-src in the CSP.yaml file.

**Reply by R-Nabil** [reply]
Hey,

Were you able to move forward with this ? I have indeed experiences many ban from crowdsec, which I thought was due to a bad install but seems to be due to many 40x errors thrown out.

I'll be using your draft for now ! Thanks

**Reply by chiragkrishna** [reply]
@micbar hey even i am facing the same issue. uploading multiple files ask for basic auth. here is my csp.yaml

```
directives:
  child-src:
    - "'self'"
  connect-src:
    - "'self'"
    - "blob:"
    - "https://raw.githubusercontent.com/opencloud-eu/awesome-apps/"
    - "https://redacted-authentik/"
  default-src:
    - "'none'"
  font-src:
    - "'self'"
  frame-ancestors:
    - "'self'"
  frame-src:
    - "'self'"
    - "blob:"
    - "https://embed.diagrams.net/"
    - "https://redacted-collabora/"
    - "https://docs.opencloud.eu"
  img-src:
    - "'self'"
    - "data:"
    - "blob:"
    - "https://raw.githubusercontent.com/opencloud-eu/awesome-apps/"
    - "https://redacted-collabora/"
  manifest-src:
    - "'self'"
  media-src:
    - "'self'"
  object-src:
    - "'self'"
    - "blob:"
  script-src:
    - "'self'"
    - "'unsafe-inline'"
    - "https://redacted-authentik/"
  style-src:
    - "'self'"
    - "'unsafe-inline'"
```

**Reply by micbar** [reply]
Looks fine from a quick read. Can you check your browser console and network tab for errors?

**Reply by chiragkrishna** [reply]
thanks, i checked the errors in browser console.
these are the errors
```ini
1) Refused to frame "https://redacted-authentik/" because it violates the following Content Security Policy directive:
"frame-src 'self' blob: https://embed.diagrams.net/ https://redacted-collabora/ https://docs.opencloud.eu".

2) https://unpkg.com/echarts@6.0.0/dist/echarts.min.js blocked script-src-elem

3) CSP blocks the use of 'eval' in JavaScript
```

is this the correct way to solve the problem?
my new csp.yaml
```yaml
directives:
  child-src:
    - "'self'"
  connect-src:
    - "'self'"
    - "blob:"
    - "https://raw.githubusercontent.com/opencloud-eu/awesome-apps/"
    - "https://redacted-authentik/"
  default-src:
    - "'none'"
  font-src:
    - "'self'"
  frame-ancestors:
    - "'self'"
  frame-src:
    - "'self'"
    - "blob:"
    - "https://embed.diagrams.net/"
    - "https://redacted-collabora/"
    - "https://docs.opencloud.eu"
    - "https://redacted-authentik/"      <----- Added
  img-src:
    - "'self'"
    - "data:"
    - "blob:"
    - "https://raw.githubusercontent.com/opencloud-eu/awesome-apps/"
    - "https://redacted-collabora/"
  manifest-src:
    - "'self'"
  media-src:
    - "'self'"
  object-src:
    - "'self'"
    - "blob:"
  script-src:
    - "'self'"
    - "https://unpkg.com"      <----- Added
    - "'unsafe-eval'"      <----- Added
    - "'unsafe-inline'"
    - "https://redacted-authentik/"
  style-src:
    - "'self'"
    - "'unsafe-inline'"
```
