### DISCUSSION TITLE
Docker Compose: Minimal Collabora setup

### DISCUSSION THREAD

**Discussion by SHU-red** [opencloud-eu/opencloud#805] [Q&A] [answered]
I am currently running
- a very minimal setup
- no ssl/https/proxy
- onlyoffice documentserver already running in docker independently and accessible via `http://192.168.178.55:3006`

Can anyone tell me what env vars i have to set to use the documentserver?

I am struggling a bit with the documentation right now, not knowing if i have to use the "collabora" env vars and/or have to get the external web app storage going first

The "full example" for docker is a bit overwhealming for me and i do not use clone, but only use portainer/stacks because i do only want to define the stuff i really need by myself

Thanks a lot in advance

```yml
services:
  server:
    image: opencloudeu/opencloud-rolling:latest
    container_name: opencloud
    environment:
      - OC_INSECURE=true
      - PROXY_HTTP_ADDR=0.0.0.0:9200
      - OC_URL=https://192.168.178.55:9200
    restart: always
    volumes:
      - oc_config:/etc/opencloud:Z
      - oc_data:/var/lib/opencloud:Z
    ports:
      - '9200:9200'

volumes:
  oc_config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.57,nolock,soft,rw,nfsvers=4.2"
      device: ":/mnt/tank/tank/opencloud/config/"
  oc_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.57,nolock,soft,rw,nfsvers=4.2"
      device: ":/mnt/tank/tank/opencloud/data/"
```
