### DISCUSSION TITLE
Collabora - ProofKeys verification failed

### DISCUSSION THREAD

**Discussion by SvenC56** [opencloud-eu/opencloud#917] [Q&A]
I'm trying to connect the opencloud collaboration server to collabora but I get this weird error on the collaboration server. If I try to open the specific page in the web it returns a 500 code.
```
{"level":"error","service":"collaboration","request-id":"","proto":"HTTP/1.1","method":"GET","path":"/wopi/files/6722505ec1d4c900bbe2b5f7afd9606c4e882b2ca9cb0890119f31c570c8a72d","WopiSessionId":"","WopiOverride":"","WopiProof":"","WopiProofOld":"","WopiStamp":"","FileReference":"resource_id:{storage_id:\"b417af62-2ce7-4c01-bb43-981860260855\" opaque_id:\"c081e2ef-a207-4cd1-9ceb-4ba120b525e1\" space_id:\"6c92344d-5381-4832-9bbc-c3c750b74d4b\"} path:\".\"","ViewMode":"VIEW_MODE_READ_WRITE","Requester":"idp:\"https://xxx/application/o/opencloud-desktop/\" opaque_id:\"7edb1054-260a-4c64-9b0a-cd54a76331fe\" type:USER_TYPE_PRIMARY","error":"Invalid timestamp","time":"2025-05-22T21:01:26Z","line":"github.com/opencloud-eu/opencloud/services/collaboration/pkg/middleware/proofkeys.go:58","message":"ProofKeys verification failed"}
```

what confuses me is this part:
```
"error":"Invalid timestamp"
```

does anyone else had this issue?

my config is pretty straight forward:
````yaml
  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    command: ['coolconfig generate-proof-key && /start-collabora-online.sh --port=80']
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/80 && echo -e 'GET /hosting/discovery HTTP/1.1\r\nHost: localhost:80\r\n\r\n' >&3 && head -n 1 <&3 | grep '200 OK'"]
    # dns: "172.28.0.20"
    cap_add:
    - MKNOD
    volumes
    - ./collabora/fonts:/opt/collaboraoffice/share/fonts/truetype
    environment:
      domain: opencloud_collaboration:9300
      DONT_GEN_SSL_CERT: "YES"
      extra_params: |
        --o:ssl.enable=false \
        --o:ssl.ssl_verification=false \
        --o:ssl.termination=true \
        --o:welcome.enable=false \
        --o:net.frame_ancestors=opencloud.xxx.de
        --port=80
      username: admin
      password: admin

  opencloud_collaboration:
    image: opencloudeu/opencloud-rolling:2.3.0
    container_name: opencloud_collaboration
    depends_on:
      opencloud:
        condition: service_started
      collabora:
        condition: service_healthy
    entrypoint:
      - /bin/sh
    command: [ "-c", "opencloud collaboration server" ]
    environment:
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      MICRO_REGISTRY: "nats-js-kv"
      MICRO_REGISTRY_ADDRESS: "opencloud:9233"
      COLLABORATION_WOPI_SRC: http://opencloud_collaboration:9300
      COLLABORATION_APP_NAME: "CollaboraOnline"
      COLLABORATION_APP_PRODUCT: "Collabora"
      COLLABORATION_APP_ADDR: http://collabora.xxx.de
      COLLABORATION_APP_ICON: http://collabora.xxx.de/favicon.ico
      COLLABORATION_APP_INSECURE: "true"
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "true"
      COLLABORATION_LOG_LEVEL: info
      OC_URL: https://opencloud.xxx.de
...


````

thank you!
