### DISCUSSION TITLE
Not logged in

### DISCUSSION THREAD

**Discussion by eXtreme-by** [opencloud-eu/opencloud#955] [General]
Server is running without traefic. everything works behind its reverse proxy.
When accessing by ip, everything is ok. 
When accessing the domain name when trying to log in, an error appears on the screen:

> Not logged in
> 
> This could be because of a routine safety log out, or because your account is either inactive or not yet authorized for use. Please try logging in after a while or seek help from your Administrator.

started with [https://github.com/opencloud-eu/opencloud-compose/?tab=readme-ov-file#behind-external-proxy](url)

in the logs:

`ERR failed to authenticate the request | service=proxy error=failed to verify access token: Get "https://ххххххххххххххх/.well-known/openid-configuration": EOF authenticator=oidc path=/ocs/v2.php/apps/notifications/api/v1/notifications/sse user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:139.0) Gecko/20100101 Firefox/139.0 client.address=хххххххххххххххх network.peer.address= network.peer.port= line=github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/oidc_auth.go:198`

**Comment by eXtreme-by** [comment]
nextcloud, owncloud, immich  works on my network without any problems. opencloud is not working.

**Reply by micbar** [reply]
Seems that your opencloud container cannot connect to `https://ххххххххххххххх/.well-known/openid-configuration`

Please check that with `curl` inside the opencloud container.

If that doesn't work, you need to check your reverse proxy configuration, that opencloud can resolve its own public domain.

**Reply by eXtreme-by** [reply]
`docker exec -it opencloud-compose-opencloud-1 curl -v https://mydomain/.well-known/openid-configuration
* Host mydomain:443 was resolved.
* IPv6: (none)
* IPv4: myip
*   Trying myip:443...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLS connect error: error:00000000:lib(0)::reason(0)
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mydomain:443
* closing connection #0
curl: (35) TLS connect error: error:00000000:lib(0)::reason(0)
`

My reverse proxy handles the certificates. any other services work fine. opencloud stubbornly seems to want his own.
Please help me

**Reply by micbar** [reply]
Did you set PROXY_TLS=false ?

**Reply by eXtreme-by** [reply]
written in docker-compose.yml: PROXY_TLS=false

**Reply by eXtreme-by** [reply]
changed it to "true". nothing has changed. on the "Not logged in" screen. curl inside the opencloud container = TLS connect error.
[https://ibb.co/hxCgXH1r](url)

**Reply by micbar** [reply]
You neee to debug the connection error. Something  in the stack prevents it.

**Reply by micbar** [reply]
> nextcloud, owncloud, immich works on my network without any problems. opencloud is not working.

Ok. I know them. Have contributed on some of them 😉. All of them are not using openIDConnect.
OpenCloud brings an IdP, which is mandatory.

The public url of that IdP needs to be protected by an officially signed certificate that all components (proxies, clients, services) can trust. If curl throws an error on your url, that it is maybe not a problem of curl or openCloud but a problem of the certificate.

**Reply by micbar** [reply]
Maybe the reverse proxy doesn’t expose the public SSL certificate on internal connections?

**Reply by eXtreme-by** [reply]
Tell me something. I don't know where to look anymore.

**Reply by eXtreme-by** [reply]
> Maybe the reverse proxy doesn’t expose the public SSL certificate on internal connections?

Hmmm, is there any way to check this?

**Reply by eXtreme-by** [reply]
the certificate was issued by Let's Encrypt.
nextcloud is working fine on this domain with this certificate.

**Reply by micbar** [reply]
I do not know your reverse proxy config. We need more details to help you.

**Comment by msys5** [comment]
I am experiencing the same problem.
I am trying to run Opencloud using traefik which is already set up.

My opencloud/compose.yml is as follows
```
services:
  opencloud:
    image: ${OC_DOCKER_IMAGE:-opencloudeu/opencloud-rolling}:${OC_DOCKER_TAG:-latest}
    container_name: opencloud
    networks:
      - vlan
    entrypoint:
      - /bin/sh
    command: ["-c", "opencloud init || true; opencloud server"]
    environment:
      OC_ADD_RUN_SERVICES: ${START_ADDITIONAL_SERVICES}
      OC_URL: https://opencloud.my.domain
      OC_LOG_LEVEL: ${LOG_LEVEL:-info}
      OC_LOG_COLOR: "${LOG_PRETTY:-false}"
      OC_LOG_PRETTY: "${LOG_PRETTY:-false}"
      PROXY_TLS: "false"
      OC_INSECURE: "true"
      PROXY_ENABLE_BASIC_AUTH: "true"
      IDM_ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin}" # this overrides the admin password from the configuration file
      IDM_CREATE_DEMO_USERS: "${DEMO_USERS:-false}"
      OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt
    volumes:
      - ./config/opencloud/csp.yaml:/etc/opencloud/csp.yaml:Z
      - ./config/opencloud/banned-password-list.txt:/etc/opencloud/banned-password-list.txt:Z
      # configure the .env file to use own paths instead of docker internal volumes
      - ./config:/etc/opencloud:Z
      - ./data:/var/lib/opencloud:Z
      - ./config/opencloud/apps:/var/lib/opencloud/web/assets/apps:Z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opencloud.entrypoints=websecure"
      - "traefik.http.routers.opencloud.rule=Host(`opencloud.my.domain`)"
      - "traefik.http.routers.opencloud.service=opencloud"
      - "traefik.http.services.opencloud.loadbalancer.server.port=9200"
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always

networks:
  vlan:
    external: true
```

And the traefik/compose.yml is as follows
```
services:
  traefik:
    image: "traefik:v3.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls=true"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--providers.file.watch=true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic-conf.yml:/etc/traefik/dynamic_conf/conf.yml:ro
      - /home/forest/ca/ca/opencloud:/ca/opencloud:ro
    labels:
      traefik.enable: true
      traefik.http.routers.dashboard.rule: Host(`traefik.my.domain`)
      traefik.http.routers.dashboard.entrypoints: web
      traefik.http.routers.dashboard.service: api@internal
    networks:
      vlan:
        ipv4_address: 172.18.0.10

networks:
  vlan:
    external: true
```

The traefik/dynamic-co.yml is as follows
```
tls:
  certificates:
    - certFile: /ca/opencloud/server.crt
      keyFile: /ca/opencloud/server.key
      stores:
        - default
```

The certificate is self-signed.
And since the root certificate is installed on my Windows, I believe the certificate is working fine.

![{C68012AF-1757-46C6-A91B-398EEC23D28F}](https://github.com/user-attachments/assets/bf230803-6a46-431a-aa56-d6cac88d0778)

**Reply by micbar** [reply]
Please post the logs from the opencloud container when clicking "Log in again".

**Reply by msys5** [reply]
The log after clicking ‘Log in again’ is as follows.

```
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"838632193bdf/XWB06lhe00-000109","traceid":"178b92c10044176c5a28587e9f295a99","remote-addr":"192.168.5.112","method":"GET","status":302,"path":"/signin/v1/identifier/_/authorize","duration":45.064919,"bytes":0,"time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"838632193bdf/XWB06lhe00-000111","traceid":"d255435dbb4f709b2be23e911974691d","remote-addr":"192.168.5.112","method":"GET","status":200,"path":"/oidc-callback.html","duration":1.307243,"bytes":384,"time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"838632193bdf/XWB06lhe00-000113","traceid":"fe2b3f27d49e3f83e911ce8514ee688c","remote-addr":"192.168.5.112","method":"GET","status":200,"path":"/web-oidc-callback","duration":3.142033,"bytes":3333,"time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"f9ace823-a18b-489f-9005-009d57f3530c","traceid":"6bcf8dc99d0da680e023958573634f96","remote-addr":"192.168.5.112","method":"GET","status":200,"path":"/config.json","duration":1.916111,"bytes":327,"time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"838632193bdf/XWB06lhe00-000115","traceid":"50b7c57c85f46d4c01c6d9a0ae988835","remote-addr":"192.168.5.112","method":"GET","status":200,"path":"/favicon.ico","duration":1.641898,"bytes":3333,"time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"6185d518-cdf0-4129-9ce2-1443305e9f2f","traceid":"5ac0cc0077f01075b863696205cf1944","remote-addr":"192.168.5.112","method":"GET","status":200,"path":"/themes/opencloud/theme.json","duration":2.079777,"bytes":3775,"time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
{"level":"info","service":"frontend","pkg":"rhttp","traceid":"c99a3b188cd197979a81f07db3acd9ef","time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/reva/v2@v2.33.1/internal/http/interceptors/auth/auth.go:195","message":"skipping auth check for: /app/list"}
{"level":"warn","service":"frontend","pkg":"rhttp","traceid":"c99a3b188cd197979a81f07db3acd9ef","time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/reva/v2@v2.33.1/internal/http/interceptors/auth/auth.go:248","message":"core access token not set"}
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"72b22766-e425-4a87-9d16-953721ca51eb","traceid":"090300e413f582c14b070ab70f190905","remote-addr":"192.168.5.112","method":"GET","status":200,"path":"/app/list","duration":3.088161,"bytes":17,"time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"838632193bdf/XWB06lhe00-000117","traceid":"57408be33c2587029d5049e86bd1590e","remote-addr":"192.168.5.112","method":"GET","status":200,"path":"/.well-known/openid-configuration","duration":1.103958,"bytes":1851,"time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"838632193bdf/XWB06lhe00-000119","traceid":"9ab9041458a929867400fd653ba433b6","remote-addr":"192.168.5.112","method":"POST","status":200,"path":"/konnect/v1/token","duration":32.990911,"bytes":2467,"time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
{"level":"error","service":"proxy","error":"failed to verify access token: Get \"https://opencloud.my.domain/.well-known/openid-configuration\": dial tcp 111.89.70.171:443: connect: connection refused","authenticator":"oidc","path":"/ocs/v1.php/cloud/capabilities","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36","client.address":"192.168.5.112","network.peer.address":"","network.peer.port":"","time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/oidc_auth.go:198","message":"failed to authenticate the request"}
{"level":"info","service":"frontend","pkg":"rhttp","traceid":"7fa29e369f2c4edc8bca0d28b01aa57f","time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/reva/v2@v2.33.1/internal/http/interceptors/auth/auth.go:195","message":"skipping auth check for: /ocs/v1.php/cloud/capabilities"}
{"level":"warn","service":"frontend","pkg":"rhttp","traceid":"7fa29e369f2c4edc8bca0d28b01aa57f","time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/reva/v2@v2.33.1/internal/http/interceptors/auth/auth.go:248","message":"core access token not set"}
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"12d59f32-8861-412a-a88e-57f006237a44","traceid":"ab33c63cc0704dec70ad2f3461a29fc5","remote-addr":"192.168.5.112","method":"GET","status":200,"path":"/ocs/v1.php/cloud/capabilities","duration":27.476757,"bytes":3225,"time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
{"level":"error","service":"proxy","error":"failed to verify access token: Get \"https://opencloud.my.domain/.well-known/openid-configuration\": dial tcp 111.89.70.171:443: connect: connection refused","authenticator":"oidc","path":"/api/v0/settings/roles-list","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36","client.address":"192.168.5.112","network.peer.address":"","network.peer.port":"","time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/oidc_auth.go:198","message":"failed to authenticate the request"}
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"c3fcfeda-2c6c-4c54-aa08-5d9177e8c6d8","traceid":"465dae22ec811da148464b0acd61b279","remote-addr":"192.168.5.112","method":"POST","status":401,"path":"/api/v0/settings/roles-list","duration":21.038621,"bytes":0,"time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
{"level":"error","service":"proxy","error":"failed to verify access token: Get \"https://opencloud.my.domain/.well-known/openid-configuration\": dial tcp 111.89.70.171:443: connect: connection refused","authenticator":"oidc","path":"/graph/v1.0/me","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36","client.address":"192.168.5.112","network.peer.address":"","network.peer.port":"","time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/oidc_auth.go:198","message":"failed to authenticate the request"}
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"ea1a2f22-c5cf-433e-b8a8-369774ccaf32","traceid":"ac5517440ce34e6f8e64bf9f0b54089d","remote-addr":"192.168.5.112","method":"GET","status":401,"path":"/graph/v1.0/me","duration":40.652183,"bytes":0,"time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
```

**Reply by micbar** [reply]
OpenCloud cannot connect to itself `{"level":"error","service":"proxy","error":"failed to verify access token: Get \"https://opencloud.my.domain/.well-known/openid-configuration\": dial tcp 111.89.70.171:443: connect: connection refused","authenticator":"oidc","path":"/api/v0/settings/roles-list","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36","client.address":"192.168.5.112","network.peer.address":"","network.peer.port":"","time":"2025-06-20T08:12:19Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/oidc_auth.go:198","message":"failed to authenticate the request"}
`

This needs to be fixed in your proxy setup.

**Reply by msys5** [reply]
Specifying the DNS IP address in my `compose.yml` solved the problem.
Thank you.

```
services:
  opencloud:
    image: ${OC_DOCKER_IMAGE:-opencloudeu/opencloud-rolling}:${OC_DOCKER_TAG:-latest}
    container_name: opencloud
    networks:
      - vlan
     
    # Added
    dns:
      - 192.168.5.11
```
