### ISSUE TITLE
Docker-compose example due to traefik unable to container find IP

### ISSUE THREAD

**Issue by Meri3252** [opencloud-eu/opencloud#1002]
## Describe the bug

Following the guide [here](https://docs.opencloud.eu/docs/admin/getting-started/container/docker-compose/) to setup opencloud with docker-compose, the resulting containers fail to start successfully with traefik showing the followign errors:

> 
> 2025-06-05T09:38:23Z ERR error="service \"collaboration\" error: unable to find the IP address for the container \"/opencloud_full_collaboration_1\": the server is ignored" container=collaboration-opencloud-full-c2fc7f214aba02092519406004f08de1345be64ba6a1b82231d175fbe2c1951d providerName=docker
> 2025-06-05T09:38:23Z ERR error="service \"opencloud\" error: unable to find the IP address for the container \"/opencloud_full_opencloud_1\": the server is ignored" container=opencloud-opencloud-full-1cb02e0c18ec4c24f940f953fd39b97074f15158b0fd077bd4a9b22797ad6d02 providerName=docker

Additionally it seems the opencloud container is started twice (or if that's intentional, two containers have the same name)

## Steps to reproduce
1. Follow the guide [here](https://docs.opencloud.eu/docs/admin/getting-started/container/docker-compose/) 

## Expected behavior

The example deployment should work out of the box

## Actual behavior
A clear and concise description of what happened.

The server does not start with the above errors

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

https://docs.opencloud.eu/docs/admin/getting-started/container/docker-compose

## Additional context

Docker running on Debian Bookworm

As a side note, the README.md [here](https://github.com/opencloud-eu/opencloud/blob/main/deployments/examples/opencloud_full/README.md) uses an outdated URL that needs to replace "docker" with "container" to work

**Comment by ghost** [comment]
There is also https://github.com/opencloud-eu/opencloud-compose which does not align with the documented guide

When following this second docker-compose guide and adding the entries in the hosts file, it results in a different error on the webpage "Missing or invalid config". The error above still remains as well

**Comment by micbar** [comment]
Please check if the openCloud container is up and running. This error can occur when the container is restarting due to errors during the initialization.

**Comment by ghost** [comment]
The openCloud container keeps restarting.

Here is the log file of the container:

[logfile.txt](https://github.com/user-attachments/files/20639332/logfile.txt)

**Comment by b3ncher** [comment]
I am having the same issues, trying for days now to get it to work. As OP i followed both routes, the official docs and the opencloud-compose repository, with or without external proxy: i always end up breaking down errors to 
```
traefik-1        | 2025-07-10T19:40:05Z ERR error="service \"opencloud\" error: unable to find the IP address for the container \"/opencloud_full-opencloud-1\": the server is ignored"
```
as well as 
```
opencloud-1      | 2025-07-10T19:39:57Z ERR check failed error="'web reachability': could not connect to http server: Get \"http://127.0.0.1:9280\": dial tcp 127.0.0.1:9280: connect: connection refused" line=github.com/opencloud-eu/opencloud/pkg/handlers/checker.go:107 service=ocm
```
which should be the result of the other error. Tried with minimal setup as well, same result for this and the compose repository way. 

After a lot of fiddling, this is my final compose. Would love to get some insight if this really might be a bug? Any help/advice much appreciated since i'd love to test OpenCloud <3

```
name: opencloud_full
services:
  clamav:
    image: clamav/clamav:latest
    logging:
      driver: local
    networks:
      opencloud:
    restart: always
    volumes:
      - type: bind
        source: /mnt/opencloud/main/clamav/socket
        target: /tmp
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/clamav/db
        target: /var/lib/clamav
        bind:
          create_host_path: true
  collabora:
    cap_add:
      - MKNOD
    command:
      - coolconfig generate-proof-key && /start-collabora-online.sh
    entrypoint:
      - /bin/bash
      - -c
    environment:
      DONT_GEN_SSL_CERT: "YES"
      aliasgroup1: https://wopiserver.my.domain:443
      extra_params: |
        --o:ssl.enable=false \
        --o:ssl.ssl_verification=false \
        --o:ssl.termination=true \
        --o:welcome.enable=false \
        --o:net.frame_ancestors=my.domain
      password: admin
      username: admin
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - "exec 3<>/dev/tcp/127.0.0.1/9980 && echo -e 'GET /hosting/discovery HTTP/1.1\r\nHost: localhost:9980\r\n\r\n' >&3 && head -n 1 <&3 | grep '200 OK'"
    image: collabora/code:25.04.2.1.1
    labels:
      traefik.enable: "true"
      traefik.http.routers.collabora.entrypoints: https
      traefik.http.routers.collabora.rule: Host(`collabora.my.domain`)
      traefik.http.routers.collabora.service: collabora
      traefik.http.routers.collabora.tls.certresolver: http
      traefik.http.services.collabora.loadbalancer.server.port: "9980"
    logging:
      driver: local
    networks:
      opencloud:
    restart: always
  collaboration:
    command:
      - -c
      - opencloud collaboration server
    depends_on:
      collabora:
        condition: service_healthy
        required: true
      opencloud:
        condition: service_started
        required: true
    entrypoint:
      - /bin/sh
    environment:
      COLLABORATION_APP_ADDR: https://collaboramy.domain
      COLLABORATION_APP_ICON: https://collabora.my.domain/favicon.ico
      COLLABORATION_APP_INSECURE: "true"
      COLLABORATION_APP_NAME: CollaboraOnline
      COLLABORATION_APP_PRODUCT: Collabora
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "true"
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      COLLABORATION_LOG_LEVEL: info
      COLLABORATION_WOPI_SRC: https://wopiserver.my.domain
      MICRO_REGISTRY: nats-js-kv
      MICRO_REGISTRY_ADDRESS: opencloud:9233
      OC_URL: https://my.domain
    image: opencloudeu/opencloud-rolling:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.collaboration.entrypoints: https
      traefik.http.routers.collaboration.rule: Host(`wopiserver.my.domain`)
      traefik.http.routers.collaboration.service: collaboration
      traefik.http.routers.collaboration.tls.certresolver: http
      traefik.http.services.collaboration.loadbalancer.server.port: "9300"
    logging:
      driver: local
    networks:
      opencloud:
    restart: always
    volumes:
      - type: bind
        source: /mnt/opencloud/main/config
        target: /etc/opencloud
        bind:
          create_host_path: true
  drawio-init:
    command:
      - -c
      - cp -R /usr/share/nginx/html/draw-io/ /apps
    entrypoint:
      - /bin/sh
    image: opencloudeu/web-extensions:draw-io-1.0.0
    networks:
      opencloud:
    user: root
    volumes:
      - type: bind
        source: /mnt/opencloud/main/apps
        target: /apps
        bind:
          create_host_path: true
  externalsites-init:
    command:
      - -c
      - cp -R /usr/share/nginx/html/external-sites/ /apps
    entrypoint:
      - /bin/sh
    image: opencloudeu/web-extensions:external-sites-1.0.0
    networks:
      opencloud:
    user: root
    volumes:
      - type: bind
        source: /mnt/opencloud/main/apps
        target: /apps
        bind:
          create_host_path: true
  jsonviewer-init:
    command:
      - -c
      - cp -R /usr/share/nginx/html/json-viewer/ /apps
    entrypoint:
      - /bin/sh
    image: opencloudeu/web-extensions:json-viewer-1.0.0
    networks:
      opencloud:
    user: root
    volumes:
      - type: bind
        source: /mnt/opencloud/main/apps
        target: /apps
        bind:
          create_host_path: true
  keycloak:
    command:
      - start
      - --proxy=edge
      - --spi-connections-http-client-default-disable-trust-manager=false
      - --import-realm
    depends_on:
      postgres:
        condition: service_started
        required: true
    entrypoint:
      - /bin/sh
      - /opt/keycloak/bin/docker-entrypoint-override.sh
    environment:
      KC_DB: postgres
      KC_DB_PASSWORD: keycloak
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_FEATURES: impersonation
      KC_HOSTNAME: key.my.domain
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      OC_DOMAIN: my.domain
    image: quay.io/keycloak/keycloak:25.0.0
    labels:
      traefik.enable: "true"
      traefik.http.routers.keycloak.entrypoints: https
      traefik.http.routers.keycloak.rule: Host(`key.my.domain`)
      traefik.http.routers.keycloak.service: keycloak
      traefik.http.routers.keycloak.tls.certresolver: http
      traefik.http.services.keycloak.loadbalancer.server.port: "8080"
    logging:
      driver: local
    networks:
      opencloud:
    restart: always
    volumes:
      - type: bind
        source: /mnt/opencloud/main/opencloud/deployments/examples/opencloud_full/config/keycloak/docker-entrypoint-override.sh
        target: /opt/keycloak/bin/docker-entrypoint-override.sh
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/opencloud/deployments/examples/opencloud_full/config/keycloak/opencloud-realm-autoprovisioning.dist.json
        target: /opt/keycloak/data/import-dist/opencloud-realm.json
        bind:
          create_host_path: true
  ldap-manager:
    environment:
      APP_URL: https://ldap.my.domain
      LDAP_HOST: ldap-server
      LDAP_LOGIN_OBJECTCLASS: inetOrgPerson
      LDAP_PORT: "1389"
    image: phpldapadmin/phpldapadmin:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.ldap-manager.entrypoints: https
      traefik.http.routers.ldap-manager.rule: Host(`ldap.my.domain`)
      traefik.http.routers.ldap-manager.service: ldap-manager
      traefik.http.routers.ldap-manager.tls.certresolver: http
      traefik.http.services.ldap-manager.loadbalancer.server.port: "8080"
    logging:
      driver: local
    networks:
      opencloud:
    restart: always
  ldap-server:
    entrypoint:
      - /bin/sh
      - /opt/bitnami/scripts/openldap/docker-entrypoint-override.sh
      - /opt/bitnami/scripts/openldap/run.sh
    environment:
      BITNAMI_DEBUG: "true"
      LDAP_ADMIN_PASSWORD: 56834211aB
      LDAP_ENABLE_TLS: "yes"
      LDAP_ROOT: dc=opencloud,dc=eu
      LDAP_TLS_CA_FILE: /opt/bitnami/openldap/share/openldap.crt
      LDAP_TLS_CERT_FILE: /opt/bitnami/openldap/share/openldap.crt
      LDAP_TLS_KEY_FILE: /opt/bitnami/openldap/share/openldap.key
      LDAP_TLS_VERIFY_CLIENT: never
    image: bitnami/openldap:2.6
    logging:
      driver: local
    networks:
      opencloud:
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 1389
        published: "389"
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 1636
        published: "636"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /mnt/opencloud/main/data/empty-dir
        target: /ldifs
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/opencloud/deployments/examples/opencloud_full/config/ldap/docker-entrypoint-override.sh
        target: /opt/bitnami/scripts/openldap/docker-entrypoint-override.sh
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/ldap/certs
        target: /opt/bitnami/openldap/share
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/ldap/data
        target: /bitnami/openldap
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/opencloud/deployments/examples/opencloud_full/config/ldap/ldif/10_base.ldif
        target: /ldifs/10_base.ldif
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/opencloud/deployments/examples/shared/config/ldap/schemas/10_opencloud_schema.ldif
        target: /schemas/10_opencloud_schema.ldif
        bind:
          create_host_path: true
  opencloud:
    command:
      - -c
      - opencloud init || true; opencloud server
    depends_on:
      drawio-init:
        condition: service_completed_successfully
        required: true
      externalsites-init:
        condition: service_completed_successfully
        required: true
      jsonviewer-init:
        condition: service_completed_successfully
        required: true
      progressbars-init:
        condition: service_completed_successfully
        required: true
      unzip-init:
        condition: service_completed_successfully
        required: true
    entrypoint:
      - /bin/sh
    environment:
      ANTIVIRUS_CLAMAV_SOCKET: /var/run/clamav/clamd.sock
      ANTIVIRUS_MAX_SCAN_SIZE: 6GB
      ANTIVIRUS_MAX_SCAN_SIZE_MODE: partial
      ANTIVIRUS_SCANNER_TYPE: clamav
      COLLABORA_DOMAIN: collabora.my.domain
      COMPANION_DOMAIN: companion.opencloud.test
      FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: eu.opencloud.api.collaboration.CollaboraOnline
      FRONTEND_ARCHIVER_MAX_SIZE: "10000000000"
      FRONTEND_FULL_TEXT_SEARCH_ENABLED: "true"
      FRONTEND_READONLY_USER_ATTRIBUTES: user.onPremisesSamAccountName,user.displayName,user.mail,user.passwordProfile,user.memberOf
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      GRAPH_ASSIGN_DEFAULT_USER_ROLE: "false"
      GRAPH_AVAILABLE_ROLES: b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6
      GRAPH_LDAP_GROUP_CREATE_BASE_DN: ou=custom,ou=groups,dc=opencloud,dc=eu
      GRAPH_LDAP_REFINT_ENABLED: "true"
      GRAPH_LDAP_SERVER_UUID: "false"
      GRAPH_USERNAME_MATCH: none
      IDM_ADMIN_PASSWORD: admin
      IDM_CREATE_DEMO_USERS: "false"
      IDP_DEFAULT_SIGNIN_PAGE_TEXT: ""
      KEYCLOAK_DOMAIN: key.my.domain
      MICRO_REGISTRY_ADDRESS: 127.0.0.1:9233
      NATS_NATS_HOST: 0.0.0.0
      NATS_NATS_PORT: "9233"
      OC_ADD_RUN_SERVICES: notifications,antivirus
      OC_ADMIN_USER_ID: ""
      OC_EXCLUDE_RUN_SERVICES: idm
      OC_INSECURE: "false"
      OC_LDAP_BIND_DN: cn=admin,dc=opencloud,dc=eu
      OC_LDAP_BIND_PASSWORD: 56834211aB
      OC_LDAP_DISABLE_USER_MECHANISM: attribute
      OC_LDAP_GROUP_BASE_DN: ou=groups,dc=opencloud,dc=eu
      OC_LDAP_GROUP_SCHEMA_ID: opencloudUUID
      OC_LDAP_INSECURE: "true"
      OC_LDAP_SERVER_WRITE_ENABLED: "true"
      OC_LDAP_URI: ldaps://ldap-server:1636
      OC_LDAP_USER_BASE_DN: ou=users,dc=opencloud,dc=eu
      OC_LDAP_USER_FILTER: (objectclass=inetOrgPerson)
      OC_LDAP_USER_SCHEMA_ID: opencloudUUID
      OC_LOG_COLOR: "true"
      OC_LOG_LEVEL: info
      OC_LOG_PRETTY: "true"
      OC_OIDC_ISSUER: https://key.my.domain/realms/OpenCloud
      OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt
      OC_URL: https://my.domain
      POSTPROCESSING_STEPS: virusscan
      PROXY_AUTOPROVISION_ACCOUNTS: "true"
      PROXY_AUTOPROVISION_CLAIM_USERNAME: sub
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/opencloud/csp.yaml
      PROXY_ENABLE_BASIC_AUTH: "false"
      PROXY_OIDC_REWRITE_WELLKNOWN: "true"
      PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
      PROXY_TLS: "false"
      PROXY_USER_CS3_CLAIM: username
      PROXY_USER_OIDC_CLAIM: sub
      SEARCH_EXTRACTOR_TIKA_TIKA_URL: http://tika:9998
      SEARCH_EXTRACTOR_TYPE: tika
      SETTINGS_SETUP_DEFAULT_ASSIGNMENTS: "false"
      STORAGE_USERS_DATA_GATEWAY_URL: http://opencloud:9200/data
      WEB_OIDC_CLIENT_ID: web
      WEB_OPTION_ACCOUNT_EDIT_LINK_HREF: https://key.my.domain/realms/OpenCloud/account
    image: opencloudeu/opencloud-rolling:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.opencloud.entrypoints: https
      traefik.http.routers.opencloud.rule: Host(`my.domain`)
      traefik.http.routers.opencloud.service: opencloud
      traefik.http.routers.opencloud.tls.certresolver: http
      traefik.http.services.opencloud.loadbalancer.server.port: "9200"
    logging:
      driver: local
    networks:
      opencloud:
    restart: always
    volumes:
      - type: bind
        source: /mnt/opencloud/main/opencloud/deployments/examples/opencloud_full/config/opencloud/app-registry.yaml
        target: /etc/opencloud/app-registry.yaml
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/opencloud/deployments/examples/opencloud_full/config/opencloud/csp.yaml
        target: /etc/opencloud/csp.yaml
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/opencloud/deployments/examples/opencloud_full/config/opencloud/banned-password-list.txt
        target: /etc/opencloud/banned-password-list.txt
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/config
        target: /etc/opencloud
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/data
        target: /var/lib/opencloud
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/clamav/socket
        target: /var/run/clamav
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/apps
        target: /var/lib/opencloud/web/assets/apps
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/opencloud/deployments/examples/opencloud_full/config/opencloud/apps.yaml
        target: /etc/opencloud/apps.yaml
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/opencloud/deployments/examples/opencloud_full/config/opencloud/proxy.yaml
        target: /etc/opencloud/proxy.yaml
        bind:
          create_host_path: true
  postgres:
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
    image: postgres:alpine
    logging:
      driver: local
    networks:
      opencloud:
    restart: always
    volumes:
      - type: bind
        source: /mnt/opencloud/main/keycloak/keycloak_postgres_data
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
  progressbars-init:
    command:
      - -c
      - cp -R /usr/share/nginx/html/progress-bars/ /apps
    entrypoint:
      - /bin/sh
    image: opencloudeu/web-extensions:progress-bars-1.0.0
    networks:
      opencloud:
    user: root
    volumes:
      - type: bind
        source: /mnt/opencloud/main/apps
        target: /apps
        bind:
          create_host_path: true
  radicale:
    image: opencloudeu/radicale:latest
    logging:
      driver: local
    networks:
      opencloud:
    restart: always
    volumes:
      - type: bind
        source: /mnt/opencloud/main/opencloud/deployments/examples/opencloud_full/config/radicale/config
        target: /etc/radicale/config
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/radicale/data
        target: /var/lib/radicale
        bind:
          create_host_path: true
  tika:
    image: apache/tika:latest
    logging:
      driver: local
    networks:
      opencloud:
    restart: always
  traefik:
    command:
      - --log.level=ERROR
      - --certificatesResolvers.http.acme.email=me@some.where
      - --certificatesResolvers.http.acme.storage=/certs/acme.json
      - --certificatesResolvers.http.acme.keyType=EC256
      - --certificatesResolvers.http.acme.dnsChallenge.provider=netcup
      - --certificatesResolvers.http.acme.dnsChallenge.resolvers=9.9.9.9:53,9.9.9.11:53
      - --certificatesResolvers.http.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --api.dashboard=false
      - --entryPoints.http.address=:80
      - --entryPoints.http.http.redirections.entryPoint.to=https
      - --entryPoints.http.http.redirections.entryPoint.scheme=https
      - --entryPoints.https.address=:443
      - --entryPoints.https.transport.respondingTimeouts.readTimeout=12h
      - --entryPoints.https.transport.respondingTimeouts.writeTimeout=12h
      - --entryPoints.https.transport.respondingTimeouts.idleTimeout=3m
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedByDefault=false
      - --accessLog=true
      - --accessLog.format=json
      - --accessLog.fields.headers.names.X-Request-Id=keep
    environment:
      NETCUP_API_KEY: "xxx"
      NETCUP_API_PASSWORD: "xxx"
      NETCUP_CUSTOMER_NUMBER: "xxx"
      NETCUP_POLLING_INTERVAL: "60"
      NETCUP_PROPAGATION_TIMEOUT: "1800"
    image: traefik:v3.3.1
    labels:
      traefik.enable: "true"
      traefik.docker.network: "opencloud"
      traefik.http.middlewares.traefik-auth.basicauth.users: admin:$$apr1$$4vqie50r$$YQAmQdtmz5n9rEALhxJ4l.
      traefik.http.routers.traefik.entrypoints: https
      traefik.http.routers.traefik.middlewares: traefik-auth
      traefik.http.routers.traefik.rule: Host(`traefik.opencloud.test`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.tls.certresolver: http
    logging:
      driver: local
    networks:
      opencloud:
        aliases:
          - my.domain
          - collabora.my.domain
          - wopiserver.my.domain
          - key.my.domain
          - ldap.my.domain
    ports:
      - mode: ingress
        target: 80
        published: "80"
        protocol: tcp
      - mode: ingress
        target: 443
        published: "443"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/main/certs
        target: /certs
        bind:
          create_host_path: true
  unzip-init:
    command:
      - -c
      - cp -R /usr/share/nginx/html/unzip/ /apps
    entrypoint:
      - /bin/sh
    image: opencloudeu/web-extensions:unzip-1.0.2
    networks:
      opencloud:
    user: root
    volumes:
      - type: bind
        source: /mnt/opencloud/main/apps
        target: /apps
        bind:
          create_host_path: true
networks:
  opencloud:
    name: opencloud
    driver: overlay
    external: true
    attachable: true

```
