### ISSUE TITLE
Not redirect to user home page after authentication using external OIDC

### ISSUE THREAD

**Issue by StafLoker** [opencloud-eu/opencloud#1011]
## Describe the bug
Not redirect to user home page after authentication using external OIDC. Is stop in `Logging you in
Please wait, you are being redirected.` page.

![Image](https://github.com/user-attachments/assets/2b7ea902-2214-416f-b9ec-9691e1bc0924)

URL: `https://drive.domain.com/web-oidc-callback?code=65920e14a<rest of code>&state=14218e8439a4<rest of state>`

## Steps to reproduce
1. Go to root of opencloud page, for example `https://drive.domain.com`
2. Redirect to SSO page (in my case Authentik)
3. After successful login redirect to opencloud instance
4. Stop on Redirected page

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

### Opencloud version: v2.3.0

```
sudo wget -P /usr/local/bin https://github.com/opencloud-eu/opencloud/releases/download/v2.2.0/opencloud-2.2.0-linux-amd64

sudo chmod a+x /usr/local/bin/opencloud-2.2.0-linux-amd64

sudo ln -s -f /usr/local/bin/opencloud-2.2.0-linux-amd64 /usr/local/bin/opencloud

opencloud version --skip-services

sudo useradd --system --no-create-home --shell=/sbin/nologin opencloud

sudo mkdir -p /var/lib/opencloud

sudo chown opencloud:opencloud -R /var/lib/opencloud

sudo mkdir -p /etc/opencloud

sudo -u opencloud touch /etc/opencloud/opencloud.env

sudo chown -R opencloud:opencloud -R /etc/opencloud

sudo -u opencloud vim /etc/opencloud/opencloud.env

OC_URL=https://drive.domain.com
DEMO_USERS=false
PROXY_HTTP_ADDR=0.0.0.0:7750
PROXY_TLS=false
OC_INSECURE=false

OC_LOG_LEVEL=warn

OC_CONFIG_DIR=/etc/opencloud
OC_BASE_DATA_PATH=/var/lib/opencloud

sudo -u opencloud opencloud init --config-path /etc/opencloud --insecure=false

sudo systemctl edit --force --full opencloud.service

[Unit]
Description=OpenCloud server

[Service]
Type=simple
User=opencloud
Group=opencloud
EnvironmentFile=/etc/opencloud/opencloud.env
ExecStart=/usr/local/bin/opencloud server
Restart=always

[Install]
WantedBy=multi-user.target

sudo systemctl daemon-reload

sudo systemctl enable --now opencloud

sudo systemctl restart opencloud

sudo journalctl -f -u opencloud
```

Reverse proxy

```
sudo vim /etc/nginx/sites-available/drive.domain.com

server {
    listen 80;
    listen [::]:80;
    server_name drive.domain.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name drive.potereniy.casa;
    
    ssl_certificate /etc/letsencrypt/live/drive.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/drive.domain.com/privkey.pem; # managed by Certbot

    set $upstream http://127.0.0.1:7750;

    location / {
        proxy_buffers 4 256k;
        proxy_buffer_size 128k;
        proxy_busy_buffers_size 256k;

        # Disable checking of client request body size
        client_max_body_size 0;

        include /etc/nginx/snippets/proxy.conf;
        proxy_pass $upstream;
    }
}

sudo ln -s /etc/nginx/sites-available/drive.domain.com  /etc/nginx/sites-enabled

sudo nginx -t
sudo systemctl restart nginx.service 
```

Env. config

```
# General
OC_URL=https://drive.domain.com
PROXY_HTTP_ADDR=0.0.0.0:7750
PROXY_TLS=false
OC_INSECURE=false

DEMO_USERS=false

OC_LOG_LEVEL=warn

OC_CONFIG_DIR=/etc/opencloud
OC_BASE_DATA_PATH=/var/lib/opencloud

# SSO
OC_OIDC_ISSUER=https://auth.domain.com/application/o/opencloud/
WEB_OIDC_CLIENT_ID=DiEYchhJEHk9TDkg4Hpa2mQUKOWZR2JO6X3TvEiu
## Proxy
PROXY_AUTOPROVISION_ACCOUNTS=true
PROXY_ROLE_ASSIGNMENT_DRIVER="oidc"
PROXY_OIDC_REWRITE_WELLKNOWN="true"
PROXY_USER_OIDC_CLAIM="preferred_username"
PROXY_USER_CS3_CLAIM="username"
## role assignment
OC_EXCLUDE_RUN_SERVICES=idp
WEB_OIDC_SCOPE=openid profile email groups
PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM=groups
GRAPH_ASSIGN_DEFAULT_USER_ROLE=false
GRAPH_USERNAME_MATCH="none"

# CSP
PROXY_CSP_CONFIG_FILE_LOCATION=/etc/opencloud/csp.yaml

# EMAIL
# Define SMTP settings if you would like to send OpenCloud email notifications.
# SMTP host to connect to.
NOTIFICATIONS_SMTP_HOST=smtp.maileroo.com
# Port of the SMTP host to connect to.
NOTIFICATIONS_SMTP_PORT=587
# An eMail address that is used for sending OpenCloud notification eMails
# like "opencloud notifications <noreply@yourdomain.com>".
NOTIFICATIONS_SMTP_SENDER=drive@domain.com
# Username for the SMTP host to connect to.
NOTIFICATIONS_SMTP_USERNAME=drive@domain.com
# Password for the SMTP host to connect to.
NOTIFICATIONS_SMTP_PASSWORD=<password>
# Authentication method for the SMTP communication.
NOTIFICATIONS_SMTP_AUTHENTICATION=login
# Encryption method for the SMTP communication. Possible values are 'starttls', 'ssltls' and 'none'
NOTIFICATIONS_SMTP_ENCRYPTION=starttls
# Allow insecure connections to the SMTP server. Defaults to false.
NOTIFICATIONS_SMTP_INSECURE=false

# Addititional services to be started on opencloud startup
# The following list of services is not startet automatically and must be
# manually defined for startup:
# IMPORTANT: The notification service is MANDATORY, do not delete!
# IMPORTANT: Add any services to the startup list comma separated like "notifications,antivirus" etc.
OC_ADD_RUN_SERVICES="notifications"
```

Proxy.yaml

```yaml
role_assignment:
  driver: oidc
  oidc_role_mapper:
    role_claim: groups
    role_mapping:
      - role_name: admin 
        claim_value: Drive Admins
      - role_name: spaceadmin
        claim_value: Drive Admins 
      - role_name: user
        claim_value: Drive
      - role_name: guest
        claim_value: Guests 
```

csp.yaml 

```
directives:
  child-src:
    - '''self'''
  connect-src:
    - '''self'''
    - 'blob:'
    - 'https://raw.githubusercontent.com/opencloud-eu/awesome-apps/'
    - 'https://auth.domain.com/'
  default-src:
    - '''none'''
  font-src:
    - '''self'''
  frame-ancestors:
    - '''self'''
  frame-src:
    - '''self'''
    - 'blob:'
    # This is needed for the external-sites web extension when embedding sites
    - 'https://docs.opencloud.eu'
  img-src:
    - '''self'''
    - 'data:'
    - 'blob:'
    - 'https://raw.githubusercontent.com/opencloud-eu/awesome-apps/'
  manifest-src:
    - '''self'''
  media-src:
    - '''self'''
  object-src:
    - '''self'''
    - 'blob:'
  script-src:
    - '''self'''
    - '''unsafe-inline'''
  style-src:
    - '''self'''
    - '''unsafe-inline'''
```

## Authentik provider configuration

Authentik version: 2025.6.0

![Image](https://github.com/user-attachments/assets/44dadee6-8d6d-45bc-97bf-edb7e8ae2c79)
![Image](https://github.com/user-attachments/assets/e54b6ed1-80ce-420b-9f46-00240a2a35bc)
![Image](https://github.com/user-attachments/assets/a628dffd-2fa9-4062-af2c-07905e08e869)
![Image](https://github.com/user-attachments/assets/4cb5fa10-40a5-4e0c-9973-0958ef5eab21)
![Image](https://github.com/user-attachments/assets/df4ed90e-277e-4d4b-a170-478defc4dff4)
