### ISSUE TITLE
cifs mounted directory as data directory does not allow personal data to be stored

### ISSUE THREAD

**Issue by msys5** [opencloud-eu/opencloud#1081]
## Describe the bug
If you designate a Windows shared folder `cifs` mounted directory as your data directory, your personal data will disappear.

![Image](https://github.com/user-attachments/assets/2695289e-ed77-476b-9bc5-a5a8ec323bcc)

## Steps to reproduce
1.Set up a shared folder in Windows.
2.Configure `cifs` mount in `fstab` on Ubuntu (Docker Host).
3.Specify the mounted directory as the data directory in `compose.yml` and `compose up`.

## Expected behavior
If you specify a local directory instead of a mounted directory, you will see a tab for personal data.
![Image](https://github.com/user-attachments/assets/9da3bb1c-75ca-46b1-8fca-d1a9ac2296b3)

## Setup
`compose.yml`
```
services:
  opencloud:
    image: opencloudeu/opencloud-rolling:latest
    container_name: opencloud
    networks:
      - vlan
    dns:
      - 192.168.5.11
    entrypoint:
      - /bin/sh
    command: ["-c", "opencloud init || true; opencloud server"]
    environment:
      OC_ADD_RUN_SERVICES: ${START_ADDITIONAL_SERVICES}
      OC_URL: https://opencloud.forest-sv.f5.si
      OC_LOG_LEVEL: info
      OC_LOG_COLOR: "false"
      OC_LOG_PRETTY: "false"
      PROXY_TLS: "false"
      OC_INSECURE: "true"
      PROXY_ENABLE_BASIC_AUTH: "true"
      IDM_ADMIN_PASSWORD: "admin"
      IDM_CREATE_DEMO_USERS: "false"
      OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt
    volumes:
      - ./config/opencloud/csp.yaml:/etc/opencloud/csp.yaml
      - ./config/opencloud/banned-password-list.txt:/etc/opencloud/banned-password-list.txt
      - ./config:/etc/opencloud:Z
      - ./config/opencloud/apps:/var/lib/opencloud/web/assets/apps:Z
      - /mnt/opencloud/data:/var/lib/opencloud:Z
      #- ./data:/var/lib/opencloud:Z   ## This setting will work properly.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opencloud.entrypoints=websecure"
      - "traefik.http.routers.opencloud.rule=Host(`opencloud.my.domain`)"
      - "traefik.http.routers.opencloud.service=opencloud"
      - "traefik.http.services.opencloud.loadbalancer.server.port=9200"
    logging:
      driver: local
    restart: always

networks:
  vlan:
    external: true
```

`/etc/fstab`
```
//192.168.5.10/opencloud  /mnt/opencloud  cifs  username=admin,password=admin,file_mode=0777,dir_mode=0777,mfsymlinks,uid=1000,gid=1000 0 0
```
