### ISSUE TITLE
Mardown Image Link

### ISSUE THREAD

**Issue by DennisFaucher** [opencloud-eu/opencloud#1094]
## Describe the bug
What is the correct format for inserting an image link into a markdown file in OpenCloud?

## Steps to reproduce
I have tried links to local images and Internet images and none of them display the image

I would rather use a link than upload an image as uploading inserts an extremely long string into my markdown file

## Actual behavior
A clear and concise description of what happened.

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>
<p>

```console
OC_XXX=somevalue
OC_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

**Comment by AlexAndBear** [comment]
Local images aka from your opencloud is not yet possible, as they aren't public accessible.

From the internet you can use this dialog:
*** you might need to update your csp file***
```
e.G. Content-Security-Policy: img-src * data: blob:;

```

<img width="1080" alt="Image" src="https://github.com/user-attachments/assets/920eb96f-f098-4292-a8d6-39980aa0bd97" />

<img width="1444" alt="Image" src="https://github.com/user-attachments/assets/69261305-536f-4b31-8828-1bf554950113" />

<img width="2010" alt="Image" src="https://github.com/user-attachments/assets/d5117bb1-078f-4946-9d17-e4b4e8b83851" />

**Comment by AlexAndBear** [comment]
I updated the csp.yaml, so in order to display images in the markdown editor, admins don't need to adjust their csp file 
https://github.com/opencloud-eu/opencloud/pull/1101

**Comment by DennisFaucher** [comment]
Thank you. I read the #1101 thread. 

What would be the process for inserting an image into markdown that is already on the OpenCloud server?

**Comment by DennisFaucher** [comment]
This did not work for me. I am using the docker-compose.yml in ./deployments/examples/opencloud_full/docker-compose.yml

<img width="1212" alt="Image" src="https://github.com/user-attachments/assets/9b0d6210-2756-4918-a8fe-c96e05a9fb18" />

**Comment by AlexAndBear** [comment]
after you adjusted the csp.yml you need to stop the container and restart it (docker compose down && docker compose up -d)

**Comment by DennisFaucher** [comment]
Can you explain where that new directive goes in csp.yaml?
e.G. Content-Security-Policy: img-src * data: blob:;


```
directives:
  child-src:
    - '''self'''
  connect-src:
    - '''self'''
    - 'blob:'
    - 'https://${COMPANION_DOMAIN|companion.opencloud.test}/'
    - 'wss://${COMPANION_DOMAIN|companion.opencloud.test}/'
    - 'https://raw.githubusercontent.com/opencloud-eu/awesome-apps/'
    - 'https://${KEYCLOAK_DOMAIN|keycloak.opencloud.test}/'
  default-src:
    - '''none'''
  font-src:
    - '''self'''
  frame-ancestors:
    - '''self'''
  frame-src:
    - '''self'''
    - 'blob:'
    - 'https://embed.diagrams.net/'
    # In contrary to bash and docker the default is given after the | character
    - 'https://${COLLABORA_DOMAIN|collabora.opencloud.test}/'
    # This is needed for the external-sites web extension when embedding sites
    - 'https://docs.opencloud.eu'
  img-src:
    - '''self'''
    - 'data:'
    - 'blob:'
    - 'https://raw.githubusercontent.com/opencloud-eu/awesome-apps/'
    # In contrary to bash and docker the default is given after the | character
    - 'https://${COLLABORA_DOMAIN|collabora.opencloud.test}/'
  manifest-src:
    - '''self'''
  media-src:
    - '''self'''
  object-src:
    - '''self'''
    - 'blob:'
  script-src:
    - '''self'''
    - '''unsafe-inline'''
  style-src:
    - '''self'''
    - '''unsafe-inline'''
```
