### ISSUE TITLE
External OIDC seems not functional

### ISSUE THREAD

**Issue by enticedwanderer** [opencloud-eu/opencloud#455]
## Describe the bug
It doesn't seem possible to utilize external IDP currently, at least not via OAUTH2/OIDC. Migrating existing configuration from previously working owncloud setup, opencloud now tries to do a XHR GET to external IDP well known location and can't because of CORS. We shouldn't be needing CORS to begin with with a normal redirect, if opencloud was doing OIDC to spec.

Perhaps I need to customize further settings? Am I missing anything else needed to get external auth functional?

## Steps to reproduce
1. Set up environment variables or config for external IDP use.
2. Set up external IDP OIDC issuer (I used Authentik)
3. Start opencloud and try to login

## Expected behavior
Opencloud should redirect me to external OIDC.

## Actual behavior
It fails with CORS error while opening a normal opencloud page.
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://authentik.home.lan/application/o/opencloud/.well-known/openid-configuration. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
```

## Setup
Standard docker setup as provided in the git repo. Additional env variables for opencloud container.

<details>
<p>

```console
      # OIDC config
      PROXY_AUTOPROVISION_ACCOUNTS: "true"
      PROXY_OIDC_REWRITE_WELLKNOWN: "true"
      PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: "none"
      OC_OIDC_ISSUER: https://authentik.home.lan/application/o/opencloud/
      WEB_OIDC_CLIENT_ID: JRf59P10id6LvrNiHDj3XGvT4DvqW2k0Kmwpjhaj
      WEB_OIDC_SCOPE: "openid profile email offline_access"
```

</p>
</details>

## Additional context
Note that removing the configuration above and falling back to internal IDP everything seems to function as expected.

**Comment by mpldr** [comment]
I think I could narrow it down to the OIDC well-known not being included in the CSP. First tests with 
```
	header Content-Security-Policy "default-src * 'unsafe-eval' 'unsafe-inline' data: filesystem: about: blob: ws: wss:"

	reverse_proxy http://127.0.1.2:9200 {
		header_down -Content-Security-Policy
	}
```
seem promising. Though, I would very much prefer to not keep this CSP.

**Comment by micbar** [comment]
In our deployment example, we include a csp.yaml file which configures the csp rules.

We have a pr to add keycloak #465 

Please let us consolidate the work there.

**Comment by micbar** [comment]
Keycloak needs to be added to `connect-src` in the openCloud csp.yaml file.

**Comment by enticedwanderer** [comment]
I was just looking at #465 and tried to double check. I don't think the issue is with the CSP (at least in my case) since:

```
root@dockerino:/docker/config/opencloud# cat config/opencloud/csp.yaml  | head -n15
directives:
  child-src:
    - '''self'''
  connect-src:
    - '''self'''
    - 'blob:'
    - 'https://${COMPANION_DOMAIN|companion.opencloud.test}/'
    - 'wss://${COMPANION_DOMAIN|companion.opencloud.test}/'
    - 'https://raw.githubusercontent.com/opencloud-eu/awesome-apps/'
    - 'https://authentik.home.lan/'
    - 'https://authentik.home.lan/application/o/opencloud/.well-known/openid-configuration'
  default-src:
    - '''none'''
  font-src:
    - '''self'''
 ```

I even added the the direct URL that's failing for good measure. I think the actual issue is that Authentik is not returning in it's response `Access-Control-Allow-Origin` header which CORS expects to find on OC side and thus fails.

I was implying that it shouldn't have to because according to spec we should be doing a redirect to OIDC instead of a XHR request.

And yes I confirmed that csp file is being used:

```
root@dockerino:/docker/config/opencloud# grep -i csp docker-compose.yml
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/opencloud/csp.yaml
      # these three vars are needed to the csp config file to include the web office apps and the importer
      - ./config/opencloud/csp.yaml:/etc/opencloud/csp.yaml
```
