### ISSUE TITLE
Disable HTTPS Traefik as entrypoint for TLS Termination

### ISSUE THREAD

**Issue by suse-coder** [opencloud-eu/opencloud#532]
## Is your feature request related to a problem? Please describe.
Currently I do TLS Termination before opencloud traefik. As I guess that is the entrypoint how can i disable that it enforces https. Can I somehow bypass traefik and direclty talk to opencloud, minio etc?

**Comment by micbar** [comment]
Yes you can do that. We show that in our opencloud_full example.

The key is to set PROXY_TLS=true

**Comment by micbar** [comment]
> Can I somehow bypass traefik and direclty talk to opencloud, minio etc?

Technically, this is possible. But not supported. You should never run any application without a reverse proxy in production.

**Comment by jochumdev** [comment]
Hey,

I'm using a yet inofficial way to install opencloud and point my own reverse proxy on it:

This is my `octoctl` config https://github.com/octocompose/octoctl

```yaml
name: opencloud01
include:
  - url: https://raw.githubusercontent.com/octocompose/charts/refs/heads/main/opencloud-monolith/config/opencloud.yaml
  - url: https://raw.githubusercontent.com/octocompose/charts/refs/heads/main/opencloud-monolith/config/collabora.yaml
  - url: https://raw.githubusercontent.com/octocompose/charts/refs/heads/main/opencloud-monolith/config/tika.yaml
  - url: https://raw.githubusercontent.com/octocompose/charts/refs/heads/main/opencloud-monolith/config/web_extensions/all.yaml
configs:
    collabora:
        admin:
            password: thatsNoSecret
            user: admin
    opencloud:
        domain:
            collabora: collabora.example.com
            companion: companion.example.com
            oc: cloud.example.com
            onlyoffice: onlyoffice.example.com
            wopiserver: wopi.example.com
        idp:
            adminPassword: thatsNoSecret
        smtp:
            authentication: plain
            host: mail.example.com
            insecure: "false"
            password: thatsNoSecret
            port: 587
            sender: OpenCloud notifications <cloud@example.com>
            username: cloud@example.com
octoctl:
  operator: docker
services:
  opencloud:
    ports:
      - 9200:9200
  collaboration:
    ports:
      - 9300:9300
  collabora:
    ports:
      - 9980:9980
```

- Save that File as `opencloud.yaml`
- Install octoctl
- Run `octoctl -c opencloud.yaml start`

When you do so please note that theres a bug with HTTP/3 enabled Traefik as front proxy: https://github.com/opencloud-eu/reva/issues/148
