### ISSUE TITLE
[Bug] Different Ingress than Traefik OnlyOffice mix traffic error

### ISSUE THREAD

**Issue by suse-coder** [opencloud-eu/opencloud#624]
## Describe the bug
When I use a different Ingress than Treafik and want to access onlyoffice, I get this error:

![Image](https://github.com/user-attachments/assets/42da35dc-8ef2-4761-b769-b5dbf908d51a)

For the route to onlyoffice I have added the Header X-Forwarded-Proto . Do I have to do something additionally?

**Comment by micbar** [comment]
> Do I have to do something additionally?

Yes. Onlyoffice and the wopiserver need to be accessed via https://

**Comment by suse-coder** [comment]
I  the only office pod I have in kubernetes:
```
{{- if .Values.onlyoffice.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opencloud.fullname" . }}-onlyoffice
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: onlyoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "opencloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: onlyoffice
  template:
    metadata:
      labels:
        {{- include "opencloud.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: onlyoffice
    spec:
      containers:
        - name: onlyoffice
          image: {{ .Values.onlyoffice.repository }}:{{ .Values.onlyoffice.tag | default "8.2.2" }}
          imagePullPolicy: {{ .Values.onlyoffice.pullPolicy | default "IfNotPresent" }}
          command: ["/bin/sh", "/entrypoint-override.sh"]
          env:
            - name: WOPI_ENABLED
              value: "{{ .Values.onlyoffice.wopi.enabled }}"
            - name: USE_UNAUTHORIZED_STORAGE
              value: "{{ .Values.onlyoffice.useUnauthorizedStorage }}"
            - name: X_FORWARDED_PROTO
              value: "https"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: onlyoffice-config
              mountPath: /entrypoint-override.sh
              subPath: entrypoint-override.sh
            - name: onlyoffice-config
              mountPath: /etc/onlyoffice/documentserver/local.dist.json
              subPath: local.json
            {{- if .Values.onlyoffice.persistence.enabled }}
            - name: onlyoffice-data
              mountPath: /var/lib/onlyoffice
            {{- end }}

```
and for the cilium route I have:
```
{{- if and .Values.cilium.httproute.enabled .Values.onlyoffice.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "opencloud.fullname" . }}-onlyoffice-httproute
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: onlyoffice
spec:
  parentRefs:
    - name: {{ .Values.cilium.httproute.gateway.name }}
      namespace: {{ .Values.cilium.httproute.gateway.namespace | default .Values.namespace }}
      sectionName: onlyoffice-https
  hostnames:
    - {{ .Values.global.domain.onlyoffice | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: X-Forwarded-Proto
                value: https
      backendRefs:
        - name: {{ include "opencloud.fullname" . }}-onlyoffice
          port: 80
{{- end }}

```

But still i get the mixed content error as when the https is tls terminated at the gateway and then reach the onlyoffice pod, then a http request is generated it seems:

![Image](https://github.com/user-attachments/assets/84345dbd-3cda-451f-8de2-6be2fbed3061)
