### ISSUE TITLE
Cannot create folders or move files, Error 415 on MKCOL/MOVE when using Traefik

### ISSUE THREAD

**Issue by nicokaiser** [opencloud-eu/opencloud#675]
## Describe the bug
Creating folders or moving files is not possible when using Traefik with OpenCloud. The MKCOL/MOVE requests produce status 415.

## Steps to reproduce
1. Deploy OpenCloud using Traefik proxy
2. Create a folder or move a file in the web interface

## Expected behavior
The folder should be created / the file should be moved

## Actual behavior

Creating folders or moving files is not possible when using Traefik with OpenCloud. The MKCOL/MOVE requests produce status 415:

```xml
<d:error xmlns:d="DAV" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\UnsupportedMediaType</s:exception>
  <s:message>extended-mkcol not supported</s:message>
  <s:errorcode></s:errorcode>
</d:error>
```

This means, folders cannot be created and files cannot be moved in the web interface when the server runs behind Traefik.

## Setup
<details>
<p>

```yaml
services:
  opencloud:
    image: opencloudeu/opencloud
    restart: always
    entrypoint:
      - /bin/sh
    command: ["-c", "opencloud init --insecure true || true; opencloud server"]
    environment:
      IDM_ADMIN_PASSWORD: ...
      IDM_CREATE_DEMO_USERS: false
      OC_URL: https://opencloud.example.com
      OC_LOG_LEVEL: error
      OC_LOG_COLOR: false
      OC_LOG_PRETTY: false
      OC_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: false
      PROXY_TLS: false
    networks:
      - traefik
    volumes:
      - data:/var/lib/opencloud
      - config:/etc/opencloud
    labels:
      traefik.enable: "true"
      traefik.http.routers.opencloud.rule: Host(`opencloud.example.com`)
      traefik.http.services.opencloud.loadbalancer.server.port: "9200"

volumes:
  data:
  config:

networks:
  traefik:
    external: true
```

</p>
</details>

## Additional context
The cause of this issue and a possible fix is already discussed in https://github.com/owncloud/ocis/issues/10809#issuecomment-2695403425
