### ISSUE TITLE
Folder upload authentication issue with Authentik IdP

### ISSUE THREAD

**Issue by raf0x** [opencloud-eu/opencloud#702]
Description:

I am migrating from Seafile to opencloud and have set up opencloud in a Docker container environment using Traefik as a reverse proxy. I have followed the provided examples but integrated my existing Authentik Identity Provider (IdP) instead of Keycloak. Authentication and login via Authentik work successfully.

However, I am encountering an issue when attempting to upload a complete folder with subfolders and files through the opencloud web interface. During the upload process, a basic authentication prompt appears, and the upload fails for folders. Uploading individual files, even large ones, works without any problems.

This issue prevents the successful migration of existing folder structures to opencloud.

Steps to Reproduce:

Set up opencloud with Authentik as the Identity Provider.
Log in to the opencloud web interface using Authentik.
Attempt to upload a folder containing subfolders and files.
Expected Behavior:

The folder and its contents should upload successfully without prompting for basic authentication during the process.

Actual Behavior:

During the folder upload, a basic authentication prompt appears, and the upload fails.

Configuration:

Here is the docker-compose service definition for the opencloud container:

```
services:
  opencloud:
    image: opencloudeu/opencloud-rolling
    container_name: opencloud-server
    restart: unless-stopped
    entrypoint:
      - /bin/sh
    # run opencloud init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the opencloud server
    command: ["-c", "opencloud server"]
    environment:
      OC_ADD_RUN_SERVICES: ${START_ADDITIONAL_SERVICES}
      OC_URL: https://${OC_DOMAIN}
      # do not use SSL between Traefik and OpenCloud
      PROXY_TLS: "false"
      # make the REVA gateway accessible to the app drivers
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      # admin user password
      IDM_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
       # make the registry available to the app provider containers
      MICRO_REGISTRY_ADDRESS: 127.0.0.1:9233
      NATS_NATS_HOST: 0.0.0.0
      NATS_NATS_PORT: 9233
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/opencloud/csp.yaml
      # these three vars are needed to the csp config file to include the web office apps and the importer
      COLLABORA_DOMAIN: ${COLLABORA_DOMAIN}
      # email server (if configured)
      NOTIFICATIONS_SMTP_HOST: "${SMTP_HOST}"
      NOTIFICATIONS_SMTP_PORT: "${SMTP_PORT}"
      NOTIFICATIONS_SMTP_SENDER: "${SMTP_SENDER}"
      NOTIFICATIONS_SMTP_USERNAME: "${SMTP_USERNAME}"
      NOTIFICATIONS_SMTP_PASSWORD: "${SMTP_PASSWORD}"
      NOTIFICATIONS_SMTP_INSECURE: "${SMTP_INSECURE}"
      NOTIFICATIONS_SMTP_AUTHENTICATION: "${SMTP_AUTHENTICATION}"
      NOTIFICATIONS_SMTP_ENCRYPTION: "${SMTP_TRANSPORT_ENCRYPTION}"
      # make collabora the secure view app
      FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: eu.opencloud.api.collaboration.CollaboraOnline
      GRAPH_AVAILABLE_ROLES: "b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6"
      # OICD
      KEYCLOAK_DOMAIN: ${OIDC_DOMAIN}  #csp
      OC_EXCLUDE_RUN_SERVICES: idp
      OC_OIDC_ISSUER: https://${OIDC_DOMAIN}/application/o/${OIDC_SLUG}/
      PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: none
      WEB_OIDC_CLIENT_ID: web
      PROXY_USER_OIDC_CLAIM: preferred_username
      PROXY_USER_CS3_CLAIM: username
      PROXY_AUTOPROVISION_ACCOUNTS: true
      PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
      PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM: groups
      PROXY_OIDC_REWRITE_WELLKNOWN: true
      WEB_OIDC_METADATA_URL: https://${OIDC_DOMAIN}/application/o/${OIDC_SLUG}/.well-known/openid-configuration
      WEB_OIDC_SCOPE: openid profile email
      #S3
      # activate decomposeds3 storage driver
      STORAGE_USERS_DRIVER: decomposeds3
      # keep system data on opencloud storage since this are only small files atm
      STORAGE_SYSTEM_DRIVER: decomposed
      # decomposeds3 specific settings
      STORAGE_USERS_DECOMPOSEDS3_ENDPOINT: ${S3_ENDPOINT}
      STORAGE_USERS_DECOMPOSEDS3_REGION: ${S3_REGION}
      STORAGE_USERS_DECOMPOSEDS3_ACCESS_KEY: ${S3_ACCESS_KEY}
      STORAGE_USERS_DECOMPOSEDS3_SECRET_KEY: ${S3_SECRET_KEY}
      STORAGE_USERS_DECOMPOSEDS3_BUCKET: ${S3_BUCKET}
      OC_LOG_LEVEL: info
      OC_LOG_COLOR: true
      OC_LOG_PRETTY: true
    volumes:
      - opencloud-config:/etc/opencloud
      - opencloud-data:/var/lib/opencloud
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opencloud.rule=Host(`${OC_DOMAIN}`)"
      - "traefik.http.routers.opencloud.entrypoints=websecure"
      - "traefik.http.routers.opencloud.tls=true"
      - "traefik.http.routers.opencloud.tls.certresolver=myresolver"
      - "traefik.http.services.opencloud.loadbalancer.server.port=9200"
      - "traefik.docker.network=traefik-net"
```

Technical Details/Logs:

The following error appears in the logs during the failed upload:
```
2025-04-18T14:57:16.587706525Z 2025-04-18T14:57:16Z ERR failed to authenticate the request error="token is expired" authenticator=oidc client.address="***, ***" line=github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/oidc_auth.go:198 network.peer.address= network.peer.port= path=/remote.php/dav/spaces/ff766477-a24a-4a8b-8edd-added81ae715$2adc84bb-d555-4c8a-8ab8-31a7a97b6b19/*** service=proxy user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3.1 Safari/605.1.15"
```

A screenshot of the authentication prompt is attached (referencing the image you provided).

![Image](https://github.com/user-attachments/assets/656fdfd1-b312-4f0c-bfdc-1de6f8fb9ea7)

Any help with resolving this issue would be greatly appreciated.
