### ISSUE TITLE
New user space creation fails for mounted nfs volume

### ISSUE THREAD

**Issue by SHU-red** [opencloud-eu/opencloud#770]
## Describe the bug
Maybe this is my fault,
but after first login, trying to create a Space, fails with:
> X-Request-Id: 108b5391-542c-4abe-b0fe-18ead5d08150

```
2025-05-04T19:42:45Z 2025-05-04T19:42:45Z ERR failed to create storage space | service=storage-users pkg=rgrpc traceid=ac7754ef1af6d3916a299c633ed2e6c0 error=Failed to set all xattrs: xattr.Set /var/lib/opencloud/storage/users/projects/85513bee-da89-4eb6-8441-2683dc756ba4 user.oc.propagation: operation not supported status={"code":15,"message":"error creating space","trace":"ac7754ef1af6d3916a299c633ed2e6c0"} request={"type":"project","name":"Sebastian","quota":{"quota_max_bytes":1000000000}}
```

## Steps to reproduce
1. Spin up instance in docker, with nfs mount for config and data
2. Try to add Space
3. Error occurs

## Expected behavior
Space is created

## Actual behavior
Error

## Setup

Docker-compose:

```yml
services:
  server:
    image: opencloudeu/opencloud-rolling:latest
    container_name: opencloud
    environment:
      - OC_INSECURE=true
      - PROXY_HTTP_ADDR=0.0.0.0:9200
      - OC_URL=https://192.168.178.55:9200
    #privileged: true
    restart: always
    volumes:
      - type: volume
        source: oc_config
        target: /etc/opencloud
        volume:
          nocopy: true
      - type: volume
        source: oc_data
        target: /var/lib/opencloud
        volume:
          nocopy: true
    ports:
      - '9200:9200'
    #command: "init || false; opencloud server"
volumes:
  oc_config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.57,nolock,soft,rw"
      device: ":/mnt/tank/tank/opencloud/config/"
  oc_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.57,nolock,soft,rw"
      device: ":/mnt/tank/tank/opencloud/data/"
```

**Comment by rhafer** [comment]
Your nfs mount does not support extended attributes. From the log you pasted:

```
error=Failed to set all xattrs: xattr.Set /var/lib/opencloud/storage/users/projects/85513bee-da89-4eb6-8441-2683dc756ba4 user.oc.propagation: operation not supported
```

The `posixfs` storage backend in opencloud needs to store some metadata in the extended attributes of the files. Depending on your NFS server it might be possible to enable extend attributes support.

As an alternative you might be able to switch to the `decomposed` or `decomposed-s3` storage backend, which do not require extended attributes.

**Comment by SHU-red** [comment]
> it might be possible to enable extend attributes support.

Im using TrueNAS SCALE with zfs, thats where my nfs mount in docker points to
Im not sure if i can "activate" extended attributes ...

**Comment by rhafer** [comment]
> Im not sure if i can "activate" extended attributes ...

I am sorry. I can't really help you with that. But to you know which NFS version your share is mounted with? To be able to use xattrs you need at least NFSv4.

As said, an alternative would be to switch to the `decomposed` storage driver. That is just a matter of setting `STORAGE_USERS_DRIVER=decomposed`

**Comment by SHU-red** [comment]
Thank you @rhafer for even taking the time!

> To be able to use xattrs you need at least NFSv4

Before asking here i made sure NFS4 is active on TrueNAS and changed the volume section of my docker-compose to

```yml
volumes:
  oc_config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.57,nolock,soft,rw,vers=4.2"
      device: ":/mnt/tank/tank/opencloud/config/"
  oc_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.57,nolock,soft,rw,vers=4.2"
      device: ":/mnt/tank/tank/opencloud/data/"
```

Same error


> alternative would be to switch to the `decomposed` storage driver.

I appreciate your alternative, and tried to find in the openCloud documentation what downsides this would have for me. Seeing your presentation @Graz, one of the benefits is that the data is stored where the "meta-data" is stored

Is the `decomposed` "mode" less good at this section?

I will also try to ask the TrueNAS community for this topic

**Comment by savely-krasovsky** [comment]
@SHU-red I use TrueNAS with OpenCloud. It works. Your UID/GID has to match on both ends.

**Comment by SHU-red** [comment]
> Your UID/GID has to match on both ends.

I have many many services already running, mounting from my truenas via nfs ... no problem

This issue i post here seems to be related to `xattrs`

Did you see the same problem and solved it?

How is your nfs-mount made?

**Comment by savely-krasovsky** [comment]
@SHU-red I tried to create Space and it went with no problem. No `xattrs` related errors in logs.

- I use Fedora CoreOS 42 with rootless Podman.
- I didn't met this problem at all.
- I mount it using systemd mounts. By default almost all new Linux distros uses NFSv4.2 by default.

```
[Unit]
Description=Mount personal directory
Before=remote-fs.target

[Mount]
What=192.168.100.3:/mnt/spool/personal
Where=/var/mnt/personal
Type=nfs

[Install]
WantedBy=remote-fs.target
```

Where `192.168.100.3` is my TrueNAS IP.

**Comment by SHU-red** [comment]
OK @savely-krasovsky,
this is super interesting and helpful

I run Fedora CoreOS `41.20250331.3.0 (CoreOS)` & `TrueNAS SCALE Fangtooth 25.04 [release]`
So our setup is very similar
Its good news that TrueNAS seems not to be the problem then?

The main difference i see is, that you mount with systemd, i use docker (compose)

Maybe i can find a solution to this

**Comment by savely-krasovsky** [comment]
@SHU-red You can check in TrueNAS that you have active NFSv4 session:

![Image](https://github.com/user-attachments/assets/033d4966-1674-4ebb-89f0-b466bcfec5bc)

I think it's about rootless setups only, but will share anyway:
- I changed UID and GID for `nfs` user to `1000` from `500`. It was important since I run **rootless** Podman under UID/GID 1000.
- I also run container itself under UID 1000 and remap container's UID 1000 into machine UID 1000:

   ```
   User=1000:1000
   UserNS=keep-id:uid=1000,gid=1000
   ```

This is my entrie Fedora Core OS Butane configuration: https://github.com/savely-krasovsky/homelab/blob/master/butane/fcos.yml.tftpl

**Comment by SHU-red** [comment]
Again, super helpful! In fact i did not know that the NFS Sessions section can show the NFS version

I checked it out and i do ONLY have NFSv3 Sessions, even if i specify nfsvers=4 or similar in docker compose

I then tried to ONLY allow NFSv4 (before it was 3&4) and rebooted my server
Then all of my services mounting NFS from my nas EXITED with errors

Seems that i have to rely on v3 and/or something prevents my docker on CoreOS to create a NFSv4 mount

Seems you pointed me into the right direction and i am currently thinking that maybe docker is somehow the problem, not being able to utilize NFSv4?

**Comment by savely-krasovsky** [comment]
It's very strange. Both Fedora CoreOS 41 and TrueNAS should support NFSv4 for ages. It's pretty old technology and is available everywhere for years. Are you sure you have all ports open? AFAIK v3 and v4 use different ports.

> Seems you pointed me into the right direction and i am currently thinking that maybe docker is somehow the problem, not being able to utilize NFSv4?

I don't think docker is the cause. For some reason your Fedora cannot mount it using NFSv4. You should research why. dmesg logs maybe, nfsd, etc.

**Comment by scetu** [comment]
I have just ran into same problem. My Data Direcotory is mounted NFS share from QNAP NAS. QNAP only supports NFS4.0/4.1 but `xattr` are available at 4.2 onvards only, so you need to mount it as NFS v4.2, I will try to switch storage driver, because my NAS does not support NFS 4.2

**Comment by SHU-red** [comment]
Nothing special defined

![Image](https://github.com/user-attachments/assets/3d1f309f-0509-4cfa-8ba2-d8b5e13d0b40)

Right now i mounted my Fedora 42 workstation (Not my CoreOS server) to TrueNAS and this is working as NFSv4

So you are right ... Problem occurs only on CoreOS system

Below my butane file

btw ... i always forget to mention that i use a uBlue Image for NVIDIA and docker being included

<details>

<summary>butane file</summary>

```yml
variant: fcos
version: 1.5.0
passwd:
  users:
    - name: core
      password_hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      ssh_authorized_keys:
        - xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
storage:
  disks: # Define Disk
    - device: /dev/nvme1n1
      wipe_table: true
      partitions:
        - label: nvme2
          number: 0 # No Explicit number
          wipe_partition_entry: true
          size_mib: 0 # Max Size
          start_mib: 0 # First Startingpoint
  filesystems: # Define Disk Filesystem
    - path: /var/mnt/nvme2
      device: /dev/disk/by-partlabel/nvme2
      format: ext4
      with_mount_unit: true
  files:
    # Host Name
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: blackpearl
    # Allow Passwords
    - path: /etc/ssh/sshd_config.d/20-enable-passwords.conf
      mode: 0644
      contents:
        inline: |
          PasswordAuthentication yes
    # System Updates
    - path: /etc/zincati/config.d/55-updates-strategy.toml
      contents:
        inline: |
          [updates]
          strategy = "periodic"
          [updates.periodic]
          time_zone = "Europe/Berlin"
          [[updates.periodic.window]]
          days = [ "Mon", "Thu" ]
          start_time = "01:00"
          length_minutes = 60
    # To be able to launch more than 30 containers
    # To add IPv6 support for matter hub container
    - path: /etc/docker/daemon.json
      contents:
        inline: |
          {
            "ipv6": true,
            "fixed-cidr-v6": "2001:db8:1::/64",
            "experimental": true,
            "ip6tables": true,
            "default-address-pools": [
              { "base": "172.17.0.0/16", "size": 16 },
              { "base": "172.18.0.0/16", "size": 16 },
              { "base": "172.19.0.0/16", "size": 16 },
              { "base": "172.20.0.0/14", "size": 16 },
              { "base": "172.24.0.0/14", "size": 16 },
              { "base": "172.28.0.0/14", "size": 16 },
              { "base": "192.168.0.0/16", "size": 20 },
              { "base": "2001:db8::/104", "size": 112 }
            ]
          }
    # Helix as default editor
    - path: /etc/profile.d/zz-default-editor.sh
      overwrite: true
      contents:
        inline: |
          export EDITOR=hx
    # Activate Lingering to run on boot
    - path: /var/lib/systemd/linger/core
      mode: 0644
    # Create Systemd for pre-configuring toolbox
    - path: /home/core/.config/systemd/user/toolbox-prepare.service
      mode: 0644
      contents:
        inline: |
          [Unit]
          Description=Create toolbox and install convenience applications
          # Run after all other services
          Wants=multi-user.target
          After=multi-user.target

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/bin/toolbox -y create
          ExecStart=/bin/toolbox -y run sudo yum -y install inxi btop pciutils ncdu vim neofetch fzf helix

          [Install]
          WantedBy=multi-user.target
      user:
        name: core
      group:
        name: core
    # Free Port 53 for PiHole !!! NOT TESTED !!!
    - path: /etc/systemd/resolved.conf
      mode: 0644
      contents:
        inline: |
          [Resolve]
          DNSStubListener=no
    - path: /etc/systemd/network/50-wired.link
      mode: 0644
      contents:
        inline: |
          [Match]
          MACAddress=xxxxxxx
          [Link]
          NamePolicy=kernel database onboard slot path
          MACAddressPolicy=persistent
          WakeOnLan=magic
  links:
    # Symlink needed to get toolbox working
    - path: /etc/localtime
      target: ../usr/share/zoneinfo/UTC
      overwrite: true
      hard: false
    # Manually enable user service
    - path: /home/core/.config/systemd/user/default.target.wants/toolbox-prepare.service
      user:
        name: core
      group:
        name: core
      target: /home/core/.config/systemd/user/toolbox-prepare.service
      hard: false
  directories:
    # For ucore rebase
    - path: /etc/ucore-autorebase
      mode: 0754
    # Create missing directories and set permissions
    - path: /home/core/.config
      mode: 0755
      user:
        name: core
      group:
        name: core
    - path: /home/core/.config/systemd
      mode: 0755
      user:
        name: core
      group:
        name: core
    - path: /home/core/.config/systemd/user
      mode: 0755
      user:
        name: core
      group:
        name: core
    - path: /home/core/.config/systemd/user/default.target.wants
      mode: 0755
      user:
        name: core
      group:
        name: core
systemd:
  units:
    # Unit for auto-rebase
    - name: ucore-unsigned-autorebase.service
      enabled: true
      contents: |
        [Unit]
        Description=uCore autorebase to unsigned OCI and reboot
        ConditionPathExists=!/etc/ucore-autorebase/unverified
        ConditionPathExists=!/etc/ucore-autorebase/signed
        After=network-online.target
        Wants=network-online.target
        [Service]
        Type=oneshot
        StandardOutput=journal+console
        ExecStart=/usr/bin/rpm-ostree rebase --bypass-driver ostree-unverified-registry:ghcr.io/ublue-os/fedora-coreos:stable-nvidia
        ExecStart=/usr/bin/touch /etc/ucore-autorebase/unverified
        ExecStart=/usr/bin/systemctl disable ucore-unsigned-autorebase.service
        ExecStart=/usr/bin/systemctl reboot
        [Install]
        WantedBy=multi-user.target
    # Enable Docker
    - name: docker.service
      enabled: true
    # Necessary Base Applications
    - name: rpm-ostree-install.service
      enabled: true
      contents: |
        [Unit]
        Description=Layer basic applications
        Wants=network-online.target
        After=network-online.target
        # We run before `zincati.service` to avoid conflicting rpm-ostree
        # transactions.
        Before=zincati.service
        ConditionPathExists=!/var/lib/%N.stamp

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        # `--allow-inactive` ensures that rpm-ostree does not return an error
        # if the package is already installed. This is useful if the package is
        # added to the root image in a future Fedora CoreOS release as it will
        # prevent the service from failing.
        ExecStart=/usr/bin/rpm-ostree install -y --allow-inactive docker-compose helix btop neofetch
        ExecStart=/bin/touch /var/lib/%N.stamp
        ExecStart=/bin/systemctl --no-block reboot

        [Install]
        WantedBy=multi-user.target
    # Enable accept_ra for ipv6 for ha-matter-hub
    - name: accept_ra.service
      enabled: true
      contents: |
        [Unit]
        Description=Set accept_ra and accept_ra_rt_info_max_plen
        Wants=network-online.target
        After=network-online.target

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/env bash -c "echo 2 > /proc/sys/net/ipv6/conf/enp5s0/accept_ra"
        ExecStart=/usr/bin/env bash -c "echo 64 > /proc/sys/net/ipv6/conf/enp5s0/accept_ra_rt_info_max_plen"

        [Install]
        WantedBy=multi-user.target
# For ipv6
kernel_arguments:
  should_exist:
    - CONFIG_IPV6_ROUTER_PREF=y
    - CONFIG_IPV6_ROUTE_INFO=y
  should_not_exist:
    - CONFIG_IPV6_ROUTER_PREF=n
    - CONFIG_IPV6_ROUTE_INFO=n
```

</details>

**Comment by scetu** [comment]
Hmm, if I change storage driver, I am still getting same error
```
services:
  opencloud:
    environment:
      STORAGE_USERS_DRIVER: decomposed
```

```
opencloud-1  | {"level":"info","service":"graph","request-id":"3ad68201-0cd0-4140-ba3e-70c8bbe937fe","time":"2025-05-07T17:47:47Z","line":"github.com/opencloud-eu/opencloud/services/graph/pkg/service/v0/drives.go:328","message":"calling create drive"}
opencloud-1  | {"level":"error","service":"storage-users","pkg":"rgrpc","traceid":"d5a81cab88db55422901e177b385f81b","error":"Failed to set all xattrs: xattr.Set /var/lib/opencloud/storage/users/projects/70516bcf-92b4-4cf5-bbc2-273bb452928b user.oc.space.name: operation not supported","status":{"code":15,"message":"error creating space","trace":"d5a81cab88db55422901e177b385f81b"},"request":{"type":"project","name":"New space","quota":{"quota_max_bytes":1000000000}},"time":"2025-05-07T17:47:47Z","line":"github.com/opencloud-eu/reva/v2@v2.29.3/internal/grpc/services/storageprovider/storageprovider.go:540","message":"failed to create storage space"}
opencloud-1  | {"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"3ad68201-0cd0-4140-ba3e-70c8bbe937fe","traceid":"d5a81cab88db55422901e177b385f81b","remote-addr":"172.18.0.1","method":"POST","status":500,"path":"/graph/v1.0/drives","duration":18.172414,"bytes":168,"time":"2025-05-07T17:47:47Z","line":"github.com/opencloud-eu/opencloud/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
```

Any idea what to change?

**Comment by savely-krasovsky** [comment]
@SHU-red I disabled NFSv3 entirely in my case. I think it will easier to debug since you won't be able to mount at all. Butane looks fine.

**Comment by SHU-red** [comment]
> Butane looks fine.

Thank you VERY much for checking this out!

I made "progress" i think!

I just tried to manually mount from coreOS via ssh and it seems that the manual `sudo mount ...` command created a connetion with v4

```bash
sudo mkdir /mnt/tank
sudo mount -t nfs 192.168.178.57:/mnt/tank/tank/ /mnt/tank
```

```
[core@blackpearl mnt]$ nfsstat -m
/var/lib/docker/volumes/forgejo_nfs_forgejo/_data from :/mnt/tank/tank/forgejo/
 Flags: rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,soft,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.178.57,mountvers=3,mountproto=tcp,local_lock=all,addr=192.168.178.57

/var/lib/docker/volumes/server_nfs_downloads/_data from :/mnt/tank/temp/downloads/
 Flags: rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,soft,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.178.57,mountvers=3,mountproto=tcp,local_lock=all,addr=192.168.178.57

/var/lib/docker/volumes/jellyfin_nfs_media/_data from :/mnt/tank/tank/media/
 Flags: rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,soft,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.178.57,mountvers=3,mountproto=tcp,local_lock=all,addr=192.168.178.57

/var/lib/docker/volumes/nextcloud_nfs_nextcloud/_data from :/mnt/tank/tank/nextcloud/
 Flags: rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,soft,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.178.57,mountvers=3,mountproto=tcp,local_lock=all,addr=192.168.178.57

/var/lib/docker/volumes/paperless-ngx_nfs_paperless/_data from :/mnt/tank/tank/paperless/
 Flags: rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,soft,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.178.57,mountvers=3,mountproto=tcp,local_lock=all,addr=192.168.178.57

/var/lib/docker/volumes/tdarr_nfs_scale/_data from :/mnt/tank/temp/tdarr_downscale/
 Flags: rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,soft,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.178.57,mountvers=3,mountproto=tcp,local_lock=all,addr=192.168.178.57

/var/lib/docker/volumes/tdarr_nfs_down/_data from :/mnt/tank/temp/downloads/
 Flags: rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,soft,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.178.57,mountvers=3,mountproto=tcp,local_lock=all,addr=192.168.178.57

/var/lib/docker/volumes/tdarr_nfs_out/_data from :/mnt/tank/temp/tdarr_out/
 Flags: rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,soft,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.178.57,mountvers=3,mountproto=tcp,local_lock=all,addr=192.168.178.57

/var/lib/docker/volumes/frigate_nfs_frigate/_data from :/mnt/tank/tank/frigate/
 Flags: rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,soft,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.178.57,mountvers=3,mountproto=tcp,local_lock=all,addr=192.168.178.57

/var/lib/docker/volumes/immich_nfs_upload_location/_data from :/mnt/tank/tank/immich/
 Flags: rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,soft,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.178.57,mountvers=3,mountproto=tcp,local_lock=all,addr=192.168.178.57

/var/lib/docker/volumes/paperless-ngx_nfs_consume/_data from :/mnt/tank/tank/paperless/consume
 Flags: rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,soft,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.178.57,mountvers=3,mountproto=tcp,local_lock=all,addr=192.168.178.57

/var/lib/docker/volumes/steam_headless_nfs_roms/_data from :/mnt/tank/tank/roms/
 Flags: rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,soft,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.178.57,mountvers=3,mountproto=tcp,local_lock=all,addr=192.168.178.57

/var/lib/docker/volumes/opencloud_oc_config/_data from :/mnt/tank/tank/opencloud/config/
 Flags: rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,soft,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.178.57,mountvers=3,mountproto=tcp,local_lock=all,addr=192.168.178.57

/var/lib/docker/volumes/opencloud_oc_data/_data from :/mnt/tank/tank/opencloud/data/
 Flags: rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,soft,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.178.57,mountvers=3,mountproto=tcp,local_lock=all,addr=192.168.178.57

/var/mnt/tank from 192.168.178.57:/mnt/tank/tank
 Flags: rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.178.55,local_lock=none,addr=192.168.178.57
```

So im back on blaming docker?

**Comment by SHU-red** [comment]
@savely-krasovsky 
DAMN i did it!!!!

Im not 100% sure what it was but i guess
- docker uses NFSv3 by default
- as i tried to change the mount, the volume was still there, so i had to: stop stack, delete volume and restart stack --> This led to the change in the volume settings
- Additionally `xattr`s are only available on NFSv4.2 (NFSv4.0 did not work)

So
- @savely-krasovsky Many thanks for your help
- @rhafer  sorry to bloat this issue but it may help in the future

Below my docker-compose now:

```yml

services:
  server:
    image: opencloudeu/opencloud-rolling:latest
    container_name: opencloud
    environment:

      - OC_INSECURE=true
      - PROXY_HTTP_ADDR=0.0.0.0:9200
      - OC_URL=https://192.168.178.55:9200
    #privileged: true
    restart: always
    volumes:

      - oc_config:/etc/opencloud:Z
      - oc_data:/var/lib/opencloud:Z
    ports:
      - '9200:9200'
    #command: "init || false; opencloud server"
volumes:
  oc_config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.57,nfsvers=4.2"
      device: ":/mnt/tank/tank/opencloud/config/"
  oc_data:

    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.57,nfsvers=4.2"
      device: ":/mnt/tank/tank/opencloud/data/"
```
