### ISSUE TITLE
a video file copied via the web is smaller than the original and therefore corrupt

### ISSUE THREAD

**Issue by cscholz** [opencloud-eu/opencloud#810]
## Describe the bug
I've recognized that when I copy a sepcific video file via web portal the new file is much smaller than the original one and by this the new file is corrupt. Unfortantely I can not reproduce the issue with guarentee but it occured just now again and I was able to greb the logs. Lines: 10-12 & 23-25

## Steps to reproduce
for now I don't know

## Setup
I'm running opencloud 2.2.0 on docker (podman) on an flat ext4 filesystem.
<details>
<p>

## Below my docker-compose config.
```
version: "3.8"
# Collabora ########################################
services:
  collabora:
    cap_add:
      - MKNOD
    command:
      - coolconfig generate-proof-key && /start-collabora-online.sh
    entrypoint:
      - /bin/bash
      - -c
    environment:
      DONT_GEN_SSL_CERT: YES
      aliasgroup1: https://wopi.domain.tld:443
      extra_params: |
        --o:ssl.enable=false \
        --o:ssl.ssl_verification=false \
        --o:ssl.termination=true \
        --o:welcome.enable=false \
        --o:net.frame_ancestors=oc.domain.tld
        --o:welcome.enable=false
      password: PASSWORD
      username: admin
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9980/hosting/discovery
    image: collabora/code:24.04.13.2.1
    ports:
      - 9980:9980
    network_mode: host
    labels:
      traefik.enable: "true"
      traefik.http.routers.collabora.entrypoints: https
      traefik.http.routers.collabora.rule: Host(`api.domain.tld`)
      traefik.http.routers.collabora.service: collabora
      traefik.http.routers.collabora.tls.certresolver: http
      traefik.http.services.collabora.loadbalancer.server.port: "9980"
    restart: always
  # Collaboration ##################################################
  collaboration:
    command:
      - -c
      - opencloud collaboration server
    depends_on:
      collabora:
        condition: service_healthy
      opencloud:
        condition: service_started
    entrypoint:
      - /bin/sh
    environment:
      COLLABORATION_APP_ADDR: https://api.domain.tld
      COLLABORATION_APP_ICON: https://api.domain.tld/favicon.ico
      COLLABORATION_APP_INSECURE: "true"
      COLLABORATION_APP_NAME: CollaboraOnline
      COLLABORATION_APP_PRODUCT: Collabora
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "true"
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      COLLABORATION_LOG_LEVEL: error
      COLLABORATION_WOPI_SRC: https://wopi.domain.tld
      MICRO_REGISTRY: nats-js-kv
      MICRO_REGISTRY_ADDRESS: 127.0.0.1:9233
      OC_URL: https://oc.domain.tld
    image: opencloudeu/opencloud-rolling:latest
    ports:
      - 9301:9301
      - 9300:9300
    network_mode: host
    labels:
      traefik.enable: "true"
      traefik.http.routers.collaboration.entrypoints: https
      traefik.http.routers.collaboration.rule: Host(`wopi.domain.tld`)
      traefik.http.routers.collaboration.service: collaboration
      traefik.http.routers.collaboration.tls.certresolver: http
      traefik.http.services.collaboration.loadbalancer.server.port: "9300"
    #    logging:
    #      driver: local
    restart: always
    volumes:
      - /docker/opencloud/config:/etc/opencloud:rw
  # draw.io ##############################################
  drawio-init:
    command:
      - -c
      - cp -R /usr/share/nginx/html/draw-io/ /apps
    entrypoint:
      - /bin/sh
    image: opencloudeu/web-extensions:draw-io-1.0.0
    user: root
    volumes:
      - /docker/opencloud/apps:/apps:rw
  # externalsites.init #####################################
  externalsites-init:
    command:
      - -c
      - cp -R /usr/share/nginx/html/external-sites/ /apps
    entrypoint:
      - /bin/sh
    image: opencloudeu/web-extensions:external-sites-1.0.0
    user: root
    volumes:
      - /docker/opencloud/apps:/apps:rw
  # jsonviewer.init ##############################################
  jsonviewer-init:
    command:
      - -c
      - cp -R /usr/share/nginx/html/json-viewer/ /apps
    entrypoint:
      - /bin/sh
    image: opencloudeu/web-extensions:json-viewer-1.0.0
    user: root
    volumes:
      - /docker/opencloud/apps:/apps:rw
  # opencloud ###############################################
  opencloud:
    command:
      - -c
      - opencloud init || true; opencloud server
    ports:
      - 9200:9200
      - 9233:9233 #changed
    network_mode: host
    depends_on:
      drawio-init:
        condition: service_completed_successfully
      externalsites-init:
        condition: service_completed_successfully
      jsonviewer-init:
        condition: service_completed_successfully
      progressbars-init:
        condition: service_completed_successfully
      unzip-init:
        condition: service_completed_successfully
    entrypoint:
      - /bin/sh
    environment:
      COLLABORA_DOMAIN: api.domain.tld
      COMPANION_DOMAIN: import.domain.tld
      #      FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: eu.opencloud.api.collaboration.CollaboraOnline
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      #      GRAPH_AVAILABLE_ROLES: b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6
      IDM_ADMIN_PASSWORD: PASSWORD
      IDM_CREATE_DEMO_USERS: "false"
      MICRO_REGISTRY_ADDRESS: 127.0.0.1:9233 #changed
      NATS_NATS_HOST: 0.0.0.0
      NATS_NATS_PORT: "9233"
      NOTIFICATIONS_SMTP_AUTHENTICATION: auto
      NOTIFICATIONS_SMTP_ENCRYPTION: starttls
      NOTIFICATIONS_SMTP_HOST: SMTP.domain.tld
      NOTIFICATIONS_SMTP_INSECURE: "false"
      NOTIFICATIONS_SMTP_PASSWORD: PASSWORD
      NOTIFICATIONS_SMTP_PORT: "587"
      NOTIFICATIONS_SMTP_SENDER: OpenCloud notifications <noreply@domain.tld>
      NOTIFICATIONS_SMTP_USERNAME: noreply@domain.tld
      OC_ADD_RUN_SERVICES: notifications
      OC_INSECURE: "false" #changed
      OC_LOG_COLOR: "true"
      OC_LOG_LEVEL: error
      OC_LOG_PRETTY: "true"
      STORAGE_USERS_POSIX_WATCH_FS: "true"
      OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt
      OC_URL: https://oc.domain.tld
      ONLYOFFICE_DOMAIN: onlyoffice.domain.tld
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/opencloud/csp.yaml
      PROXY_ENABLE_BASIC_AUTH: "false"
      PROXY_TLS: "false"
      SEARCH_EXTRACTOR_TYPE: tika
      SEARCH_EXTRACTOR_TIKA_TIKA_URL: https://search.domain.tld
      FRONTEND_FULL_TEXT_SEARCH_ENABLED: "true"
      # Keycloak START
      KEYCLOAK_DOMAIN: sso.domain.tld
      PROXY_AUTOPROVISION_ACCOUNTS: true
      PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
      OC_OIDC_ISSUER: https://sso.domain.tld/realms/openCloud
      PROXY_OIDC_REWRITE_WELLKNOWN: true
      PROXY_USER_OIDC_CLAIM: preferred_username
      GRAPH_ASSIGN_DEFAULT_USER_ROLE: false
      GRAPH_USERNAME_MATCH: none
      OC_EXCLUDE_RUN_SERVICES: idp,activitylog
      WEB_OPTION_ACCOUNT_EDIT_LINK_HREF: https://sso.domain.tld/realms/openCloud/account
      # Keycloak END
      # Link password config START
      # Disable the password policy.
      # OC_PASSWORD_POLICY_DISABLED
      # Define the minimum password length.
      # OC_PASSWORD_POLICY_MIN_CHARACTERS
      # Define the minimum number of uppercase letters.
      # OC_PASSWORD_POLICY_MIN_LOWERCASE_CHARACTERS
      # Define the minimum number of lowercase letters.
      # OC_PASSWORD_POLICY_MIN_UPPERCASE_CHARACTERS
      # Define the minimum number of digits.
      # OC_PASSWORD_POLICY_MIN_DIGITS
      # Define the minimum number of special characters.
      # OC_PASSWORD_POLICY_MIN_SPECIAL_CHARACTERS
      # Path to the ‘banned passwords list’ file.
      # OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST
      # Disable automatic Password protection for publich links
      OC_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: false
      # Link password config END            
    image: opencloudeu/opencloud-rolling:latest
    #    logging:
    #      driver: local
    restart: always
    volumes:
      - /docker/opencloud/config:/etc/opencloud:rw
      - /docker/opencloud/app-registry.yaml:/etc/opencloud/app-registry.yaml:rw
      - /docker/opencloud/apps.yaml:/etc/opencloud/apps.yaml:rw
      - /docker/opencloud/config/banned-password-list.txt:/etc/opencloud/banned-password-list.txt:rw
      - /docker/opencloud/csp.yaml:/etc/opencloud/csp.yaml:rw
      - /docker/opencloud/data:/var/lib/opencloud:rw
      - /docker/opencloud/apps:/var/lib/opencloud/web/assets/apps:rw
  # progress.init ####################################
  progressbars-init:
    command:
      - -c
      - cp -R /usr/share/nginx/html/progress-bars/ /apps
    entrypoint:
      - /bin/sh
    image: opencloudeu/web-extensions:progress-bars-1.0.0
    user: root
    volumes:
      - /docker/opencloud/apps:/apps:rw
  # unzip.init #################################
  unzip-init:
    command:
      - -c
      - cp -R /usr/share/nginx/html/unzip/ /apps
    entrypoint:
      - /bin/sh
    image: opencloudeu/web-extensions:unzip-1.0.2
    user: root
    volumes:
      - /docker/opencloud/apps:/apps:rw
  tika-init:
    image: tika:latest-full
    # release notes: https://tika.apache.org
    restart: always
    ports:
      - 9998:9998
  companion:
    image: transloadit/companion:5.5.2
    ports:
      - 3020:3020
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      COMPANION_CLIENT_ORIGINS: "true"
      COMPANION_ALLOW_LOCAL_URLS: "true"
      COMPANION_DATADIR: /tmp/companion/
      COMPANION_DOMAIN: 127.0.0.1:9200
      COMPANION_PROTOCOL: http
      COMPANION_PATH: /companion
      UPLOAD_URLS: import.domain.tld
      COMPANION_ONEDRIVE_KEY: ${COMPANION_ONEDRIVE_KEY}
      COMPANION_ONEDRIVE_SECRET: ${COMPANION_ONEDRIVE_SECRET}
      COMPANION_TUS_DEFERRED_UPLOAD_LENGTH: "false"
    volumes:
      - /docker/opencloud/companion:/tmp/companion/
networks: {}

```

## Log extract
```
01. 2025/05/09 10:59:18 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,CREATE,VIDEO.mp4.flock
02. 2025/05/09 10:59:18 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,"CLOSE_WRITE,CLOSE",VIDEO.mp4.flock
03. 2025/05/09 10:59:18 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,DELETE,VIDEO.mp4.flock
04. 2025/05/09 10:59:18 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,CREATE,VIDEO.mp4.flock
05. 2025/05/09 10:59:18 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,"CLOSE_WRITE,CLOSE",VIDEO.mp4.flock
06. 2025/05/09 10:59:18 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,DELETE,VIDEO.mp4.flock
07. 2025/05/09 10:59:18 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,CREATE,VIDEO.mp4.flock
08. 2025/05/09 10:59:18 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,"CLOSE_WRITE,CLOSE",VIDEO.mp4.flock
09. 2025/05/09 10:59:18 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,DELETE,VIDEO.mp4.flock
10. 2025-05-09T10:59:18+02:00 ERR Path() error="decomposedfs: root has no parent" path= pkg=rgrpc service=storage-users traceid=47a78868a44741016d51616fa81a5aa0
11. 2025-05-09T10:59:18+02:00 ERR failed to initiate upload error="decomposedfs: root has no parent" pkg=rgrpc service=storage-users status={"code":15,"message":"error getting upload id: decomposedfs: root has no parent","trace":"47a78868a44741016d51616fa81a5aa0"} traceid=47a78868a44741016d51616fa81a5aa0
12. 2025-05-09T10:59:18+02:00 ERR Internal Server Error code=500 name=eu.opencloud.web.ocdav request-id=b48e711c-71a6-4a8a-aec6-ac680caeeb5d service=ocdav status={"code":15,"message":"error getting upload id: decomposedfs: root has no parent","trace":"47a78868a44741016d51616fa81a5aa0"} traceid=47a78868a44741016d51616fa81a5aa0
13. 2025/05/09 10:59:18 http: superfluous response.WriteHeader call from github.com/opencloud-eu/reva/v2/internal/http/interceptors/log.(*responseLogger).WriteHeader (log.go:154)
14. 2025/05/09 10:59:37 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,CREATE,VIDEO.mp4.flock
15. 2025/05/09 10:59:37 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,"CLOSE_WRITE,CLOSE",VIDEO.mp4.flock
16. 2025/05/09 10:59:37 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,DELETE,VIDEO.mp4.flock
17. 2025/05/09 10:59:37 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,CREATE,VIDEO.mp4.flock
18. 2025/05/09 10:59:37 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,"CLOSE_WRITE,CLOSE",VIDEO.mp4.flock
19. 2025/05/09 10:59:37 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,DELETE,VIDEO.mp4.flock
20. 2025/05/09 10:59:37 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,CREATE,VIDEO.mp4.flock
21. 2025/05/09 10:59:37 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,"CLOSE_WRITE,CLOSE",VIDEO.mp4.flock
22. 2025/05/09 10:59:37 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/,DELETE,VIDEO.mp4.flock
23. 2025-05-09T10:59:37+02:00 ERR Path() error="decomposedfs: root has no parent" path= pkg=rgrpc service=storage-users traceid=1d216e0b75e2cbadaf5fef3a9bf531c2
24. 2025-05-09T10:59:37+02:00 ERR failed to initiate upload error="decomposedfs: root has no parent" pkg=rgrpc service=storage-users status={"code":15,"message":"error getting upload id: decomposedfs: root has no parent","trace":"1d216e0b75e2cbadaf5fef3a9bf531c2"} traceid=1d216e0b75e2cbadaf5fef3a9bf531c2
25. 2025-05-09T10:59:37+02:00 ERR Internal Server Error code=500 name=eu.opencloud.web.ocdav request-id=337a18d5-2e8f-40f5-ae92-dd666b36be31 service=ocdav status={"code":15,"message":"error getting upload id: decomposedfs: root has no parent","trace":"1d216e0b75e2cbadaf5fef3a9bf531c2"} traceid=1d216e0b75e2cbadaf5fef3a9bf531c2
26. 2025/05/09 10:59:37 http: superfluous response.WriteHeader call from github.com/opencloud-eu/reva/v2/internal/http/interceptors/log.(*responseLogger).WriteHeader (log.go:154)
27. 2025/05/09 10:59:45 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/.oc-nodes/locks/,CREATE,ae730a5d-6821-428f-9415-2762fbca36dc.mlock
28. 2025/05/09 10:59:45 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/.oc-nodes/locks/,"CLOSE_WRITE,CLOSE",ae730a5d-6821-428f-9415-2762fbca36dc.mlock
29. 2025/05/09 10:59:45 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/.oc-nodes/locks/,DELETE,ae730a5d-6821-428f-9415-2762fbca36dc.mlock
30. 2025/05/09 10:59:45 /var/lib/opencloud/storage/users/users/21d5bc31-3a76-4772-a3b4-edb1a37f4cd4/.oc-nodes/locks/,CREATE,83e302c4-77e0-4f8c-af72-2622cd47fd1a.mlock
```
